
import React, { createContext, useState, useContext, ReactNode } from 'react';

export type Language = 'en' | 'uz' | 'ru';

export const translations = {
  en: {
    dashboard: "Dashboard",
    patients: "Patients",
    new_patient: "New Patient",
    help: "Help",
    settings: "Settings",
    logout: "Logout",
    search: "Search...",
    dr_name: "Account Owner",
    total_patients: "Total Patients",
    new_patients_stat: "New Patients",
    total_appointments: "Total Appointments",
    requests: "Requests",
    last_month: "Last Month",
    patients_stats: "Patients Statistics",
    monthly: "Monthly",
    weekly: "Weekly",
    todays_appointments: "Today's Appointments",
    see_all: "See All",
    patient_directory: "Patient Directory",
    total: "Total",
    name: "Name",
    operation_date: "Operation Date",
    next_injection: "Next Injection",
    status: "Status",
    action: "Action",
    none_scheduled: "None Scheduled",
    view: "View",
    back_to_list: "Back to List",
    age: "Age",
    gender: "Gender",
    phone: "Phone",
    email: "Email Address",
    grafts: "Graft Count",
    technique: "Transplant Type",
    select_tech: "Select type",
    tech: "Type",
    transplant_hair: "Hair",
    transplant_eyebrow: "Eyebrow",
    transplant_beard: "Beard",
    before_operation: "Before Operation",
    progress: "Progress",
    add_photo: "Add Photo",
    injection_schedule: "Plasma Injection Schedule",
    injection: "Injection",
    mark_done: "Mark Done",
    mark_missed: "Missed",
    new_patient_reg: "New Patient Registration",
    edit_patient_title: "Edit Patient Profile",
    full_name: "Full Name",
    phone_number: "Phone Number",
    save_patient: "Save Patient",
    saving: "Saving...",
    cancel: "Cancel",
    click_upload: "Click to upload",
    patient_list: "Patient List",
    details: "Details",
    add_new_patient: "Add New Patient",
    today: "Today",
    years: "Years",
    no_image: "No Image",
    no_progress: "No progress photos yet.",
    no_upcoming: "No upcoming injections.",
    plasma_injection: "Plasma Injection",
    status_active: "Active",
    status_recovered: "Recovered",
    status_observation: "Observation",
    status_scheduled: "Scheduled",
    status_completed: "Completed",
    status_missed: "Missed",
    status_cancelled: "Cancelled",
    gender_male: "Male",
    gender_female: "Female",
    gender_other: "Other",
    add_injection: "Schedule Injection",
    edit_injection: "Edit Injection",
    date: "Date",
    notes: "Notes",
    save: "Save",
    confirm_logout_title: "Are you sure?",
    confirm_logout_desc: "Do you want to sign out of your account?",
    keep_logged_in: "Keep Logged In",
    photo_label_title: "Photo Timeline",
    time_since_op: "Time since operation",
    value: "Value",
    unit: "Unit",
    days: "Days",
    weeks: "Weeks",
    months: "Months",
    enter_notes: "Enter optional notes...",
    delete: "Delete",
    confirm_delete: "Are you sure you want to delete this injection?",
    delete_modal_title: "Are you sure?",
    delete_warning: "This action cannot be undone. Are you sure you want to permanently remove this session?",
    delete_photo_title: "Are you sure?",
    delete_photo_desc: "Do you want to permanently delete this progress photo?",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    login_welcome: "Welcome Back",
    login_subtitle: "Please enter your access code",
    enter_password: "Enter Password",
    login_btn: "Login",
    wrong_password: "Incorrect password, please try again.",
    access_restricted: "Access Restricted",
    edit_profile: "Edit Profile",
    current_password: "Current Password",
    new_password: "New Password",
    password_hint: "Use a strong password (at least 8 characters, numbers and letters)",
    optional_change: "(optional - only to change)",
    profile_photo: "Profile Photo",
    before_photo: "Clinical Photo (Before)",
    personal_info: "Personal Information",
    medical_details: "Medical Details",
    enter_patient_details: "Enter patient details below",
    upload_image: "Upload Image",
    lock_app: "Lock App",
    app_locked: "App Locked",
    enter_pin: "Enter PIN to Unlock",
    unlock: "Unlock",
    enable_lock: "Enable Lock Screen",
    lock_hint: "Adds a lock button to the sidebar for quick security.",
    security_settings: "Security Settings",
    edit_patient: "Edit Patient",
    delete_patient: "Delete Patient",
    delete_patient_confirm: "Are you sure you want to delete this patient profile? All data including photos and history will be permanently removed.",
    login_phone: "Phone Number",
    login_password: "Password",
    login_signin: "Sign In",
    login_title: "Sign in to your clinic account",
    delete_patient_title: "Delete Patient profile?",
    danger_zone: "Danger Zone",
    login_no_account: "Contact your administrator if you don't have an account",
    login_error_no_account: "No account found with this phone number",
    login_error_invalid_password: "Invalid password",
    login_error_disabled: "This account has been disabled",
    login_error_generic: "An error occurred. Please try again.",
    select_language: "Language",
    toast_profile_saved: "Profile saved successfully!",
    toast_save_failed: "Failed to save",
    toast_upload_failed: "Image upload failed",
    toast_password_short: "Password must be at least 6 characters",
    toast_no_session: "No active session - please log out and log back in",
    toast_patient_added: "Patient added successfully",
    toast_patient_updated: "Patient updated successfully",
    toast_patient_deleted: "Patient deleted successfully",
    toast_delete_failed: "Failed to delete patient",
    toast_photo_added: "Photo added successfully",
    toast_photo_deleted: "Photo deleted successfully",
    toast_injection_added: "Injection added successfully",
    toast_injection_updated: "Injection updated successfully",
    toast_injection_deleted: "Injection deleted successfully",
    toast_profile_updated: "Profile updated successfully!",
    forgot_password: "Forgot password? Sign out",
    forgot_password_link: "Forgot your password?",
    reset_password_title: "Reset Password",
    reset_password_desc: "Enter your email and we'll send you a reset link.",
    send_link: "Send Link",
    check_email: "Check your email for the reset link!",
    email_placeholder: "Email",
    magic_link_sent: "Magic link sent! Check your email to log in.",
    select_date: "Select Date",
    january: "January", february: "February", march: "March", april: "April", may: "May", june: "June",
    july: "July", august: "August", september: "September", october: "October", november: "November", december: "December",
    sun: "Su", mon: "Mo", tue: "Tu", wed: "We", thu: "Th", fri: "Fr", sat: "Sa",
    surgeries_today: "Surgeries Today",
    injections_due: "Injections Due",
    active_patients: "Active Patients",
    consultations: "Consultations",
    todays_operations: "Today's Operations",
    live_now: "Live Now",
    no_operations: "No Operations",
    view_floor_map: "View Floor Map",
    filter_all: "All",
    filter_operations: "Operations",
    filter_injections: "Injections",

    account_status: "Account Status",
    show: "Show",
    hide: "Hide",
    tomorrow: "Tomorrow",
    upcoming_patients: "Upcoming Patients",
    operation: "Operation",
    plasma_followups: "Plasma & Follow-ups",
    due_within_24h: "DUE WITHIN 24H",
    routine_followup: "Routine Follow-up",
    view_master_schedule: "View Master Schedule",
    registration_overview: "Overview of patient registration",
    upcoming_schedule: "Upcoming schedule",

    // Toasts
    toast_success_title: "Success",
    toast_error_title: "Error",
    toast_info_title: "Info",
    profile_updated_title: "Profile Updated",
    profile_updated_msg: "Your changes have been saved successfully.",
    patient_added_title: "Patient Added",
    patient_added_msg: "A new profile has been created in the database.",
    patient_updated_title: "Data Updated",
    patient_updated_msg: "Patient data has been saved perfectly.",
    deleted_title: "Deleted",
    patient_deleted_msg: "Patient data has been completely removed.",
    injection_added_title: "Injection Added",
    injection_added_msg: "New procedure successfully added to schedule.",
    photo_added_title: "Photo Added",
    photo_added_msg: "New clinical photo has been successfully saved.",
    photo_deleted_title: "Photo Deleted",
    photo_deleted_msg: "Photo has been removed from gallery.",
    status_updated_title: "Status Updated",
    status_updated_msg: "Injection status has been successfully modified.",

    // Lock Screen
    security_check: "Security Check",
    remember_password: "Doctor, can you remember the password?",

    // Delete Modal
    delete_modal_headline: "Are we really saying goodbye?",
    delete_modal_subtext: "This action cannot be undone. All patient data, photos, and history will be permanently deleted.",
    delete_modal_cancel: "No, keep it",
    delete_modal_confirm: "Yes, delete",

    // Empty States
    empty_state_peace: "Peace for now...",
    schedule_empty_title: "No Injections Yet",
    schedule_empty_mascot: "No injections scheduled yet. Let's plan the first recovery step!",
    add_first_injection: "Schedule First Injection",
    next_injection_tooltip: "Next Injection!",

    // Settings & Admin
    settings_desc: "Manage your profile, preferences, and security",
    account_id_label: "Account",
    preferences: "Preferences",
    notifications: "Notifications",
    app_appearance: "App Appearance",
    light_mode: "Light",
    security: "Security",
    two_factor: "Two-Factor Auth",
    logout_desc: "End your current session",
    admin_control_center: "Super Admin Control Center",
    god_mode: "God Mode Active",
    megaphone_title: "The Megaphone",
    megaphone_desc: "Broadcast an instant alert to every active user.",
    transmit: "Transmit",
    clear: "Clear",

    // Pagination
    pagination_showing: "Showing {start}-{end} of {total} patients",

    // Validation
    validation_name_required: "Full name is required",
    validation_phone_required: "Phone number is required",
    validation_age_invalid: "Please enter a valid age (1-120)",
    validation_technique_required: "Please select a technique",
    validation_date_required: "Operation date is required",

    // Empty State
    empty_patient_list_title: "No Patients Found",
    empty_patient_list_desc: "It looks quiet here. Add a new patient to get started!",
  },
  uz: {
    dashboard: "Boshqaruv paneli",
    patients: "Bemorlar",
    new_patient: "Yangi Bemor",
    help: "Yordam",
    settings: "Sozlamalar",
    logout: "Chiqish",
    search: "Qidirish...",
    dr_name: "Account Owner",
    total_patients: "Jami Bemorlar",
    new_patients_stat: "Yangi Bemorlar",
    total_appointments: "Jami Uchrashuvlar",
    requests: "So'rovlar",
    last_month: "O'tgan oy",
    patients_stats: "Bemorlar Statistikasi",
    monthly: "Oylik",
    weekly: "Haftalik",
    todays_appointments: "Bugungi Uchrashuvlar",
    see_all: "Hammasini ko'rish",
    patient_directory: "Bemorlar Ro'yxati",
    total: "Jami",
    name: "Ism",
    operation_date: "Operatsiya Sanasi",
    next_injection: "Keyingi Inyeksiya",
    status: "Holat",
    action: "Amal",
    none_scheduled: "Rejalashtirilmagan",
    view: "Ko'rish",
    back_to_list: "Ro'yxatga qaytish",
    age: "Yosh",
    gender: "Jins",
    phone: "Telefon",
    email: "Email Manzili",
    grafts: "Graftlar Soni",
    technique: "Operatsiya turi",
    select_tech: "Turini tanlang",
    tech: "Turi",
    transplant_hair: "Soch",
    transplant_eyebrow: "Qosh",
    transplant_beard: "Soqol",
    before_operation: "Operatsiyadan oldin",
    progress: "Jarayon",
    add_photo: "Rasm qo'shish",
    injection_schedule: "Plazma Inyeksiya Jadvali",
    injection: "Inyeksiya",
    mark_done: "Bajarildi",
    mark_missed: "O'tkazildi",
    new_patient_reg: "Yangi Bemor Ro'yxati",
    edit_patient_title: "Bemor Profilini Tahrirlash",
    full_name: "To'liq Ism",
    phone_number: "Telefon Raqami",
    save_patient: "Bemorni Saqlash",
    saving: "Saqlanmoqda...",
    cancel: "Bekor qilish",
    click_upload: "Rasm yuklash",
    patient_list: "Bemorlar Ro'yxati",
    details: "Tafsilotlar",
    add_new_patient: "Yangi Bemor Qo'shish",
    today: "Bugun",
    years: "Yosh",
    no_image: "Rasm yo'q",
    no_progress: "Hozircha jarayon rasmlari yo'q.",
    no_upcoming: "Kutilayotgan inyeksiyalar yo'q.",
    plasma_injection: "Plazma Inyeksiyasi",
    status_active: "Faol",
    status_recovered: "Tuzalgan",
    status_observation: "Kuzatuvda",
    status_scheduled: "Rejalashtirilgan",
    status_completed: "Bajarildi",
    status_missed: "O'tkazildi",
    status_cancelled: "Bekor qilindi",
    gender_male: "Erkak",
    gender_female: "Ayol",
    gender_other: "Boshqa",
    add_injection: "Inyeksiya Belgilash",
    edit_injection: "Inyeksiyani Tahrirlash",
    date: "Sana",
    notes: "Izohlar",
    save: "Saqlash",
    confirm_logout_title: "Ishonchingiz komilmi?",
    confirm_logout_desc: "Tizimdan chiqmoqchimisiz?",
    keep_logged_in: "Tizimda qolish",
    photo_label_title: "Rasm Vaqti",
    time_since_op: "Operatsiyadan o'tgan vaqt",
    value: "Qiymat",
    unit: "Birlik",
    days: "Kun",
    weeks: "Hafta",
    months: "Oy",
    enter_notes: "Izoh qoldiring...",
    delete: "O'chirish",
    confirm_delete: "Ushbu inyeksiyani o'chirmoqchimisiz?",
    delete_modal_title: "Ishonchingiz komilmi?",
    delete_warning: "Ushbu amalni ortga qaytarib bo'lmaydi. Ushbu seansni butunlay o'chirib tashlashga ishonchingiz komilmi?",
    delete_photo_title: "Ishonchingiz komilmi?",
    delete_photo_desc: "Ushbu rasm bemorning jarayon tarixidan butunlay olib tashlanadi. Ishonchingiz komilmi?",
    confirm: "Tasdiqlash",
    yes: "Ha",
    no: "Yo'q",
    login_welcome: "Xush kelibsiz",
    login_subtitle: "Iltimos, kirish kodini kiriting",
    enter_password: "Parolni kiriting",
    login_btn: "Kirish",
    wrong_password: "Parol noto'g'ri, iltimos qayta urinib ko'ring.",
    access_restricted: "Kirish Cheklangan",
    edit_profile: "Profilni Tahrirlash",
    current_password: "Joriy Parol",
    new_password: "Yangi Parol",
    password_hint: "Kuchli paroldan foydalaning (kamida 8 ta belgi, raqamlar va harflar)",
    optional_change: "(ixtiyoriy - faqat o'zgartirish uchun)",
    profile_photo: "Profil Rasmi",
    before_photo: "Klinik Rasm (Oldin)",
    personal_info: "Shaxsiy Ma'lumotlar",
    medical_details: "Tibbiy Tafsilotlar",
    enter_patient_details: "Quyida bemor tafsilotlarini kiriting",
    upload_image: "Rasm yuklash",
    lock_app: "Ilovani Qulflash",
    app_locked: "Ilova Qulflangan",
    enter_pin: "PIN kodni kiriting",
    unlock: "Ochish",
    enable_lock: "Qulf ekranini yoqish",
    lock_hint: "Xavfsizlik uchun yon panelga qulf tugmasini qo'shadi.",
    security_settings: "Xavfsizlik Sozlamalari",
    edit_patient: "Tahrirlash",
    delete_patient: "O'chirish",
    delete_patient_confirm: "Haqiqatan ham ushbu bemor profilini o'chirmoqchimisiz? Barcha ma'lumotlar, shu jumladan rasmlar va tarix butunlay o'chiriladi.",
    login_phone: "Telefon Raqami",
    login_password: "Parol",
    login_signin: "Kirish",
    login_title: "Klinika hisobingizga kiring",
    delete_patient_title: "Bemorni o'chirib tashlaysizmi?",
    danger_zone: "Xavfli Hudud",
    login_no_account: "Hisobingiz bo'lmasa, administratoringizga murojaat qiling",
    login_error_no_account: "Bu telefon raqami bilan hisob topilmadi",
    login_error_invalid_password: "Parol noto'g'ri",
    login_error_disabled: "Bu hisob o'chirilgan",
    login_error_generic: "Xatolik yuz berdi. Iltimos, qayta urinib ko'ring.",
    select_language: "Til",
    toast_profile_saved: "Profil muvaffaqiyatli saqlandi!",
    toast_save_failed: "Saqlashda xatolik",
    toast_upload_failed: "Rasm yuklashda xatolik",
    toast_password_short: "Parol kamida 6 ta belgidan iborat bo'lishi kerak",
    toast_no_session: "Faol seans yo'q - iltimos, chiqib qayta kiring",
    toast_patient_added: "Bemor muvaffaqiyatli qo'shildi",
    toast_patient_updated: "Bemor ma'lumotlari yangilandi",
    toast_patient_deleted: "Bemor muvaffaqiyatli o'chirildi",
    toast_delete_failed: "Bemorni o'chirishda xatolik",
    toast_photo_added: "Rasm muvaffaqiyatli qo'shildi",
    toast_photo_deleted: "Rasm muvaffaqiyatli o'chirildi",
    toast_injection_added: "Inyeksiya muvaffaqiyatli qo'shildi",
    toast_injection_updated: "Inyeksiya muvaffaqiyatli yangilandi",
    toast_injection_deleted: "Inyeksiya muvaffaqiyatli o'chirildi",
    toast_profile_updated: "Profil muvaffaqiyatli yangilandi!",
    forgot_password: "Parolni unutdingizmi? Chiqish",
    forgot_password_link: "Parolingizni unutdingizmi?",
    reset_password_title: "Parolni Tiklash",
    reset_password_desc: "Emailingizni kiriting, sizga qayta tiklash havolasini yuboramiz.",
    send_link: "Havola Yuborish",
    check_email: "Qayta tiklash havolasi uchun emailingizni tekshiring!",
    email_placeholder: "Email",
    forgot_password_confirm: "Parolni tiklash uchun tizimdan chiqishingiz kerak. Ma'lumotlaringiz xavfsiz saqlanadi.",
    magic_link_sent: "Sehrli havola yuborildi! Kirish uchun emailingizni tekshiring.",
    select_date: "Sanani tanlang",
    january: "Yanvar", february: "Fevral", march: "Mart", april: "Aprel", may: "May", june: "Iyun",
    july: "Iyul", august: "Avgust", september: "Sentyabr", october: "Oktyabr", november: "Noyabr", december: "Dekabr",
    sun: "Yak", mon: "Du", tue: "Se", wed: "Cho", thu: "Pay", fri: "Ju", sat: "Sha",
    surgeries_today: "Bugungi Operatsiyalar",
    injections_due: "Kutilayotgan Inyeksiyalar",
    active_patients: "Faol Bemorlar",
    consultations: "Konsultatsiyalar",
    todays_operations: "Bugungi Operatsiyalar",
    live_now: "Hozir Amalda",
    no_operations: "Operatsiyalar Yo'q",
    view_floor_map: "Xaritani Ko'rish",
    filter_all: "Barchasi",
    filter_operations: "Operatsiyalar",
    filter_injections: "Inyeksiyalar",

    current_plan: "Joriy Tarif",
    show: "Ko'rsatish",
    hide: "Yashirish",
    tomorrow: "Ertaga",
    plan_details: "Tarif Tafsilotlari",
    valid_until: "OBUNA TUGASH SANASI",
    status_not_paid: "To'lov Talab Qilinadi",
    status_trial: "Sinov Muddatida",
    transaction_history: "To'lovlar Tarixi",
    no_transactions: "Hozircha tranzaksiyalar yo'q.",
    payment_gateway: "O'zbekiston Xavfsiz To'lov Tizimi",
    subscription_fee: "Obuna To'lovi",
    pay_subscription: "Obuna uchun to'lash",


    feature_full_access: "Bemorlar ma'lumotlariga to'liq kirish",
    feature_realtime: "Ma'lumotlarni real vaqtda sinxronlash",
    feature_backups: "Avtomatik zaxira nusxalash va xavfsizlik",
    feature_sync: "Cheksiz qurilmalararo sinxronlash",
    upcoming_patients: "Kutilayotgan bemorlar",
    operation: "Operatsiya",
    plasma_followups: "Plazma va nazorat",
    due_within_24h: "24 SOAT ICHIDA",
    routine_followup: "Muntazam nazorat",
    view_master_schedule: "Asosiy jadvalni ko'rish",
    registration_overview: "Bemorlarni ro'yxatga olish sharhi",
    upcoming_schedule: "Kelgusi jadval",
    account_status: "Hisob Holati",

    // Toasts
    toast_success_title: "Sinxronizatsiya a'lo!",
    toast_error_title: "Xatolik yuz berdi",
    toast_info_title: "Bildirishnoma",
    profile_updated_title: "Profil yangilandi",
    profile_updated_msg: "Tahrirlangan ma'lumotlar muvaffaqiyatli saqlandi.",
    patient_added_title: "Bemor qo'shildi",
    patient_added_msg: "Yangi profil bazada muvaffaqiyatli yaratildi.",
    patient_updated_title: "Ma'lumot yangilandi",
    patient_updated_msg: "Bemor ma'lumotlari a'lo darajada saqlandi.",
    deleted_title: "O'chirildi",
    patient_deleted_msg: "Bemor ma'lumotlari butunlay olib tashlandi.",
    injection_added_title: "Inyeksiya qo'shildi",
    injection_added_msg: "Yangi muolaja jadvalga muvaffaqiyatli kiritildi.",
    photo_added_title: "Rasm qo'shildi",
    photo_added_msg: "Bemorning yangi jarayon fotosurati saqlandi.",
    photo_deleted_title: "Rasm o'chirildi",
    photo_deleted_msg: "Fotosurat galereyadan muvaffaqiyatli olib tashlandi.",
    status_updated_title: "Holat yangilandi",
    status_updated_msg: "Inyeksiya holati muvaffaqiyatli o'zgartirildi.",

    // Lock Screen
    security_check: "Xavfsizlik Tekshiruvi",
    remember_password: "Doktor, parolni eslay olasizmi?",

    // Delete Modal
    delete_modal_headline: "Rostdan ham xayrlashamizmi?",
    delete_modal_subtext: "Bu amalni ortga qaytarib bo'lmaydi. Bemorning barcha ma'lumotlari, rasmlari va tarixi butunlay o'chib ketadi.",
    delete_modal_cancel: "Yo'q, qolsin",
    delete_modal_confirm: "Ha, o'chirilsin",

    // Empty States
    empty_state_peace: "Hozircha tinchlik...",
    schedule_empty_title: "Hali inyeksiyalar yo'q",
    schedule_empty_mascot: "Hozircha inyeksiyalar belgilanmagan. Tiklanishning birinchi bosqichini rejalashtiramizmi?",
    add_first_injection: "Birinchi inyeksiyani belgilash",
    next_injection_tooltip: "Navbatdagi ukol!",

    // Settings & Admin
    settings_desc: "Profil, afzalliklar va xavfsizlikni boshqarish",
    account_id_label: "Hisob",
    preferences: "Afzalliklar",
    notifications: "Bildirishnomalar",
    app_appearance: "Ilova ko'rinishi",
    light_mode: "Yorug'",
    security: "Xavfsizlik",
    two_factor: "Ikki Bosqichli Himoya",
    logout_desc: "Tizimdan chiqish",
    admin_control_center: "Super Admin Markazi",
    god_mode: "Xudo rejimi faol",
    megaphone_title: "Megafon",
    megaphone_desc: "Barcha faol foydalanuvchilarga xabar yuborish.",
    transmit: "Yuborish",
    clear: "Tozalash",

    // Pagination
    pagination_showing: "Jami {total} bemordan {start}-{end} ko'rsatilmoqda",

    // Validation
    validation_name_required: "To'liq ism kiritilishi shart",
    validation_phone_required: "Telefon raqami kiritilishi shart",
    validation_age_invalid: "Iltimos, to'g'ri yoshni kiriting (1-120)",
    validation_technique_required: "Iltimos, operatsiya turini tanlang",
    validation_date_required: "Operatsiya sanasi kiritilishi shart",

    // Empty State
    empty_patient_list_title: "Hozircha Bemorlar Yo'q",
    empty_patient_list_desc: "Bu yer tinch ko'rinadi. Ishni boshlash uchun yangi bemor qo'shing!",
  },
  ru: {
    dashboard: "Панель управления",
    patients: "Пациенты",
    new_patient: "Новый пациент",
    help: "Помощь",
    settings: "Настройки",
    logout: "Выйти",
    search: "Поиск...",
    dr_name: "Владелец аккаунта",
    total_patients: "Всего пациентов",
    new_patients_stat: "Новые пациенты",
    total_appointments: "Всего приемов",
    requests: "Запросы",
    last_month: "Прошлый месяц",
    patients_stats: "Статистика пациентов",
    monthly: "Ежемесячно",
    weekly: "Еженедельно",
    todays_appointments: "Приемы сегодня",
    see_all: "Показать все",
    patient_directory: "Каталог пациентов",
    total: "Всего",
    name: "Имя",
    operation_date: "Дата операции",
    next_injection: "След. инъекция",
    status: "Статус",
    action: "Действие",
    none_scheduled: "Не запланировано",
    view: "Просмотр",
    back_to_list: "Назад к списку",
    age: "Возраст",
    gender: "Пол",
    phone: "Телефон",
    email: "Электронная почта",
    grafts: "Количество графтов",
    technique: "Пересадка",
    select_tech: "Выберите тип",
    tech: "Тип",
    transplant_hair: "Волосы",
    transplant_eyebrow: "Брови",
    transplant_beard: "Борода",
    before_operation: "До операции",
    progress: "Прогресс",
    add_photo: "Добавить фото",
    injection_schedule: "График плазмотерапии",
    injection: "Инъекция",
    mark_done: "Выполнено",
    mark_missed: "Пропущено",
    new_patient_reg: "Регистрация пациента",
    edit_patient_title: "Редактирование профиля",
    full_name: "ФИО",
    phone_number: "Номер телефона",
    save_patient: "Сохранить",
    saving: "Сохранение...",
    cancel: "Отмена",
    click_upload: "Загрузить",
    patient_list: "Список пациентов",
    details: "Детали",
    add_new_patient: "Добавить пациента",
    today: "Сегодня",
    years: "Лет",
    no_image: "Нет фото",
    no_progress: "Нет фото прогресса.",
    no_upcoming: "Нет предстоящих инъекций.",
    plasma_injection: "Плазмотерапия",
    status_active: "Активный",
    status_recovered: "Выздоровел",
    status_observation: "Наблюдение",
    status_scheduled: "Запланировано",
    status_completed: "Завершено",
    status_missed: "Пропущено",
    status_cancelled: "Отменено",
    gender_male: "Мужской",
    gender_female: "Женский",
    gender_other: "Другой",
    add_injection: "Назначить инъекцию",
    edit_injection: "Редактировать инъекцию",
    date: "Дата",
    notes: "Заметки",
    save: "Сохранить",
    confirm_logout_title: "Вы уверены?",
    confirm_logout_desc: "Вы хотите выйти из системы?",
    keep_logged_in: "Остаться в системе",
    photo_label_title: "Метка времени фото",
    time_since_op: "Время с операции",
    value: "Значение",
    unit: "Единица",
    days: "Дней",
    weeks: "Недель",
    months: "Месяцев",
    enter_notes: "Введите заметки...",
    delete: "Удалить",
    confirm_delete: "Вы уверены, что хотите удалить эту инъекцию?",
    delete_modal_title: "Вы уверены?",
    delete_warning: "Это действие нельзя отменить. Вы уверены?",
    delete_photo_title: "Вы уверены?",
    delete_photo_desc: "Вы хотите навсегда удалить это фото?",
    confirm: "Подтвердить",
    yes: "Да",
    no: "Нет",
    login_welcome: "Добро пожаловать",
    login_subtitle: "Пожалуйста, введите код доступа",
    enter_password: "Введите пароль",
    login_btn: "Войти",
    wrong_password: "Неверный пароль, попробуйте снова.",
    access_restricted: "Доступ ограничен",
    edit_profile: "Редактировать профиль",
    current_password: "Текущий пароль",
    new_password: "Новый пароль",
    password_hint: "Используйте надежный пароль (минимум 8 символов, цифры и буквы)",
    optional_change: "(необязательно - только для изменения)",
    profile_photo: "Фото профиля",
    before_photo: "Клиническое фото (До)",
    personal_info: "Личная Информация",
    medical_details: "Медицинские Детали",
    enter_patient_details: "Введите данные пациента ниже",
    upload_image: "Загрузить изображение",
    lock_app: "Блокировка",
    app_locked: "Приложение заблокировано",
    enter_pin: "Введите PIN-код",
    unlock: "Разблокировать",
    enable_lock: "Включить блокировку",
    lock_hint: "Добавляет кнопку блокировки в меню для быстрой защиты.",
    security_settings: "Настройки безопасности",
    edit_patient: "Редактировать",
    delete_patient: "Удалить",
    delete_patient_confirm: "Вы уверены, что хотите удалить профиль пациента? Все данные, включая фото и историю, будут удалены безвозвратно.",
    login_phone: "Номер телефона",
    login_password: "Пароль",
    login_signin: "Войти",
    login_title: "Войдите в аккаунт клиники",
    delete_patient_title: "Удалить профиль пациента?",
    danger_zone: "Опасная Зона",
    login_no_account: "Обратитесь к администратору, если у вас нет аккаунта",
    login_error_no_account: "Аккаунт с этим номером не найден",
    login_error_invalid_password: "Неверный пароль",
    login_error_disabled: "Этот аккаунт отключен",
    login_error_generic: "Произошла ошибка. Попробуйте снова.",
    select_language: "Язык",
    toast_profile_saved: "Профиль успешно сохранен!",
    toast_save_failed: "Не удалось сохранить",
    toast_upload_failed: "Ошибка загрузки изображения",
    toast_password_short: "Пароль должен быть не менее 6 символов",
    toast_no_session: "Нет активной сессии - выйдите и войдите снова",
    toast_patient_added: "Пациент успешно добавлен",
    toast_patient_updated: "Данные пациента обновлены",
    toast_patient_deleted: "Пациент успешно удален",
    toast_delete_failed: "Ошибка при удалении пациента",
    toast_photo_added: "Фото успешно добавлено",
    toast_photo_deleted: "Фото успешно удалено",
    toast_injection_added: "Инъекция успешно добавлена",
    toast_injection_updated: "Инъекция успешно обновлена",
    toast_injection_deleted: "Инъекция успешно удалена",
    toast_profile_updated: "Профиль успешно обновлен!",
    forgot_password: "Забыли пароль? Выйти",
    forgot_password_link: "Забыли пароль?",
    reset_password_title: "Сброс Пароля",
    reset_password_desc: "Введите email и мы отправим ссылку для сброса.",
    send_link: "Отправить",
    check_email: "Проверьте email для сброса пароля!",
    email_placeholder: "Email",
    magic_link_sent: "Ссылка отправлена! Проверьте email для входа.",
    select_date: "Выберите дату",
    january: "Январь", february: "Февраль", march: "Март", april: "Апрель", may: "Май", june: "Июнь",
    july: "Июль", august: "Август", september: "Сентябрь", october: "Октябрь", november: "Ноябрь", december: "Декабрь",
    sun: "Вс", mon: "Пн", tue: "Вт", wed: "Ср", thu: "Чт", fri: "Пт", sat: "Сб",
    surgeries_today: "Операции сегодня",
    injections_due: "Инъекции сегодня",
    active_patients: "Активные пациенты",
    consultations: "Консультации",
    todays_operations: "Сегодняшние операции",
    live_now: "Сейчас",
    no_operations: "Нет операций",
    view_floor_map: "Карта операций",
    filter_all: "Все",
    filter_operations: "Операции",
    filter_injections: "Инъекции",
    show: "Показать",
    hide: "Скрыть",
    tomorrow: "Завтра",

    current_plan: "Текущий План",
    plan_details: "Детали Плана",
    valid_until: "СРОК ПОДПИСКИ",
    status_not_paid: "Требуется Оплата",
    status_trial: "Пробный Период",
    transaction_history: "История Платежей",
    no_transactions: "Транзакций пока нет.",
    payment_gateway: "Безопасный Платежный Шлюз",
    subscription_fee: "Стоимость Подписки",
    pay_subscription: "Оплатить подписку",

    feature_full_access: "Полный доступ к записям пациентов",
    feature_realtime: "Синхронизация данных в реальном времени",
    feature_backups: "Автоматическое резервное копирование",
    feature_sync: "Синхронизация между устройствами",
    upcoming_patients: "Предстоящие пациенты",
    operation: "Операция",
    plasma_followups: "Плазма и осмотры",
    due_within_24h: "В ТЕЧЕНИЕ 24Ч",
    routine_followup: "Плановый осмотр",
    view_master_schedule: "Просмотреть общий график",
    registration_overview: "Обзор регистрации пациентов",
    upcoming_schedule: "Предстоящий график",
    account_status: "Статус Аккаунта",

    // Toasts
    toast_success_title: "Успешно!",
    toast_error_title: "Произошла ошибка",
    toast_info_title: "Информация",
    profile_updated_title: "Профиль обновлен",
    profile_updated_msg: "Ваши изменения были успешно сохранены.",
    patient_added_title: "Пациент добавлен",
    patient_added_msg: "Новый профиль успешно создан в базе данных.",
    patient_updated_title: "Данные обновлены",
    patient_updated_msg: "Данные пациента успешно сохранены.",
    deleted_title: "Удалено",
    patient_deleted_msg: "Данные пациента полностью удалены.",
    injection_added_title: "Инъекция добавлена",
    injection_added_msg: "Новая процедура успешно добавлена в график.",
    photo_added_title: "Фото добавлено",
    photo_added_msg: "Новое клиническое фото успешно сохранено.",
    photo_deleted_title: "Фото удалено",
    photo_deleted_msg: "Фотография успешно удалена из галереи.",
    status_updated_title: "Статус обновлен",
    status_updated_msg: "Статус инъекции успешно изменен.",

    // Lock Screen
    security_check: "Проверка безопасности",
    remember_password: "Доктор, вы помните пароль?",

    // Delete Modal
    delete_modal_headline: "Мы действительно прощаемся?",
    delete_modal_subtext: "Это действие нельзя отменить. Все данные пациента, фотографии и история будут удалены безвозвратно.",
    delete_modal_cancel: "Нет, оставить",
    delete_modal_confirm: "Да, удалить",

    // Empty States
    empty_state_peace: "Пока спокойно...",
    schedule_empty_title: "Инъекций пока нет",
    schedule_empty_mascot: "Инъекции еще не запланированы. Давайте запланируем первый шаг к выздоровлению!",
    add_first_injection: "Запланировать первую инъекцию",
    next_injection_tooltip: "Следующая инъекция!",

    // Settings & Admin
    settings_desc: "Управление профилем, предпочтениями и безопасностью",
    account_id_label: "Аккаунт",
    preferences: "Предпочтения",
    notifications: "Уведомления",
    app_appearance: "Внешний вид",
    light_mode: "Светлая",
    security: "Безопасность",
    two_factor: "Двухфакторная аутентификация",
    logout_desc: "Завершить текущий сеанс",
    admin_control_center: "Центр управления супер-администратора",
    god_mode: "Режим бога активен",
    megaphone_title: "Мегафон",
    megaphone_desc: "Отправить мгновенье оповещение всем активным пользователям.",
    transmit: "Отправить",
    clear: "Очистить",

    // Pagination
    pagination_showing: "Показано {start}-{end} из {total} пациентов",

    // Validation
    validation_age_invalid: "Пожалуйста, введите правильный возраст (1-120)",
    validation_technique_required: "Пожалуйста, выберите метод",
    validation_date_required: "Дата операции обязательна",

    // Empty State
    empty_patient_list_title: "Пациентов Пока Нет",
    empty_patient_list_desc: "Здесь пока тихо. Добавьте нового пациента, чтобы начать!",
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('uz');

  const t = (key: string): string => {
    // @ts-ignore
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
