

import React, { createContext, useState, useContext, ReactNode } from 'react';

export type Language = 'en' | 'uz' | 'ru';

export const translations = {
  en: {
    loading: "Loading...",
    loading_pleasewait: "Hold tight, good things are coming...",
    no_chat_selected: "No chat selected",
    select_patient_msg: "Select a patient from the left menu to view message history.",
    // Navigation
    management: "Management",
    files: "Files",
    my_files: "My Files",
    tasks_folder: "Tasks",
    notes_folder: "Notes",
    step: "Step",
    done: "Done",
    add_note_prompt: "Add a new note",
    search_files: "Search files...",
    roles: "Roles",
    roles_management: "Roles Management",
    add_user: "Add User",
    search_users: "Search users...",
    no_results_found: "No matching users found",
    no_users_found: "No users found",
    // Roles Specific
    edit_user: "Edit User",
    add_user_title: "Add New User",
    new_password_optional: "New Password (Optional)",
    leave_blank_password: "Leave blank to keep current",
    set_login_password: "Set login password",
    role_permission: "Role Permission",
    viewer_role: "Viewer",
    read_only_access: "Read-only access",
    call_operator_role: "Call Operator",
    leads_only_access: "Leads only",
    nurse_role: "Nurse",
    patients_only_access: "Patients only",
    create_account: "Create Account",
    save_changes: "Save Changes",
    remove: "Remove",
    only_admins_roles: "Only Admins can manage roles.",
    roles_management_subtitle: "Manage Viewers and Call Operators access.",

    // Roles Toasts
    toast_password_reset_note: "Note: Password update requires re-login or admin reset.",
    toast_user_added: "User successfully added as", // + role
    toast_user_updated: "User details saved successfully.",
    toast_user_removed: "User Removed",
    toast_access_revoked: "Access has been revoked.",
    toast_remove_failed: "Failed to remove user.",
    toast_phone_exists: "This phone number is already registered.",
    validation_pin_error: "Password must be exactly 6 digits.",
    set_login_password_placeholder: "Set 6-digit Login PIN",

    dashboard: "Dashboard",
    patients: "Patients",
    new_patient: "New Patient",
    help: "Help",
    settings: "Settings",
    logout: "Logout",
    search: "Search...",
    dr_name: "Account Owner",
    total_patients: "Total Patients",
    total_revenue: "Total Revenue",
    new_patients_stat: "New Patients",
    total_appointments: "Total Appointments",
    requests: "Requests",
    leads: "Leads",
    last_month: "Last Month",
    patients_stats: "Patients Statistics",
    monthly: "Monthly",
    yearly: "Yearly",
    weekly: "Weekly",
    todays_appointments: "Today's Appointments",
    see_all: "See All",
    patient_directory: "Patient Directory",
    total: "Total",
    active: "Active",
    name: "Name",
    operation_date: "Operation Date",
    next_injection: "Next Injection",

    action: "Action",
    none_scheduled: "None Scheduled",
    view: "View",
    back_to_list: "Back to List",
    edit: "Edit",
    age: "Age",
    gender: "Gender",
    phone: "Phone",
    email: "Email Address",
    grafts: "Graft Count",
    technique: "Transplant Type",
    select_tech: "Select type",
    tech: "Type",
    transplant_hair: "Hair",
    transplant_eyebrow: "Eyebrow",
    transplant_beard: "Beard",
    before_operation: "Before Operation",
    before_media: "Before Media",
    upload_photo_video: "Upload Photo/Video",
    view_photo: "View Photo",
    play_video: "Play Video",
    progress: "Progress",
    add_photo: "Add Photo",
    add_media: "Add Media",
    injection_schedule: "Plasma Injection Schedule",
    medically_verified: "Medically Verified",
    injection: "Injection",
    mark_done: "Mark Done",
    mark_missed: "Missed",
    new_patient_reg: "Guest Patient",
    edit_patient_title: "Edit Patient Profile",
    full_name: "Full Name",
    first_name: "First Name",
    last_name: "Last Name",
    phone_number: "Phone Number",
    save_patient: "Save Patient",
    saving: "Saving...",
    uploading: "Uploading...",
    cancel: "Cancel",
    click_upload: "Click to upload",
    patient_list: "Patient List",
    details: "Details",
    add_new_patient: "Add New Patient",
    journey_of_recovery: "Journey of Recovery",
    today: "Today",
    schedule: "Schedule",
    upcoming: "Upcoming",
    years: "Years",
    no_image: "No Image",
    no_progress: "No progress photos yet.",
    no_upcoming: "No upcoming injections.",
    plasma_injection: "Plasma Injection",
    status_active: "Active",
    status_recovered: "Recovered",
    status_observation: "Observation",
    status_scheduled: "Scheduled",
    status_completed: "Completed",
    status_missed: "Missed",
    status_cancelled: "Cancelled",
    gender_male: "Male",
    gender_female: "Female",
    gender_other: "Other",
    add_injection: "Schedule Injection",
    edit_injection: "Edit Injection",
    date: "Date",
    notes: "Notes",
    save: "Save",
    confirm_logout_title: "Log Out?",
    confirm_logout_desc: "Are you sure you want to sign out?",
    keep_logged_in: "Keep Logged In",
    photo_label_title: "Photo Timeline",
    time_since_op: "Time since operation",
    pinned_message: "📌 Pinned Message",
    reply_to: "Reply to",
    value: "Value",
    unit: "Unit",
    days: "Days",
    weeks: "Weeks",
    months: "Months",
    enter_notes: "Enter optional notes...",
    delete: "Delete",
    reply: "Reply",
    copy: "Copy",
    pin: "Pin",
    unpin: "Unpin",
    confirm_delete: "Are you sure you want to delete this injection?",
    delete_modal_title: "Are you sure?",
    injection_updated_title: "Injection Updated",
    injection_updated_msg: "The injection details have been successfully saved.",
    delete_photo_title: "Are you sure?",
    delete_photo_desc: "Do you want to permanently delete this progress photo?",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    login_welcome: "Welcome Back",
    login_subtitle: "Please enter your access code",
    enter_password: "Enter Password",
    login_btn: "Login",
    wrong_password: "Incorrect password, please try again.",
    access_restricted: "Access Restricted",
    edit_profile: "Edit Profile",
    current_password: "Current Password",
    new_password: "New Password",
    password_hint: "Create a 6-digit PIN code",
    optional_change: "(optional - only to change)",
    profile_photo: "Profile Photo",
    before_photo: "Clinical Photo (Before)",
    personal_info: "Personal Information",
    medical_details: "Medical Details",
    enter_patient_details: "Enter patient details below",
    upload_image: "Upload Image",
    lock_app: "Lock App",
    app_locked: "App Locked",
    enter_pin: "Enter PIN to Unlock",
    unlock: "Unlock",
    enable_lock: "Enable Lock Screen",
    lock_hint: "Adds a lock button to the sidebar for quick security.",
    security_settings: "Security Settings",
    edit_patient: "Edit Patient",
    delete_patient: "Delete Patient",
    delete_patient_confirm: "Are you sure you want to delete this patient profile? All data including photos and history will be permanently removed.",
    login_phone: "Phone Number",
    login_password: "Password",
    login_signin: "Sign In",
    login_title: "Sign in to your clinic account",
    delete_patient_title: "Delete Patient profile?",
    danger_zone: "Danger Zone",
    login_no_account: "Contact your administrator if you don't have an account",
    login_error_no_account: "No account found with this phone number",
    login_error_invalid_password: "Invalid password",
    login_error_disabled: "This account has been disabled",
    login_error_generic: "An error occurred. Please try again.",
    login_banned_msg: "Your account has been banned. Please contact the administrator.",
    schedule_message_title: "Schedule Message",
    schedule_today: "Today",
    schedule_tomorrow: "Tomorrow",
    schedule_send_today: "Send Today at",
    schedule_send_tomorrow: "Send Tomorrow at",
    schedule_send_date: "Send",
    schedule_at: "at",
    pick_date: "Pick Date",
    back: "Back",
    alert_future_time: "Please select a valid future time.",
    login_frozen_msg: "Your account has been temporarily frozen. Please contact support.",
    banned_title: "Account Restricted",
    banned_desc: "Your account has been banned due to a policy violation. Please contact the administrator for assistance.",
    banned_contact_btn: "Call Administrator",
    banned_logout: "Log Out",
    select_language: "Language",
    toast_profile_saved: "Profile saved successfully!",
    toast_save_failed: "Failed to save",
    toast_upload_failed: "Image upload failed",
    toast_password_short: "Password must be at least 6 characters",
    toast_no_session: "No active session - please log out and log back in",
    toast_patient_added: "Patient added successfully",
    toast_patient_updated: "Patient updated successfully",
    toast_patient_deleted: "Patient deleted successfully",
    toast_delete_failed: "Failed to delete patient",
    toast_photo_added: "Photo added successfully",
    toast_photo_deleted: "Photo deleted successfully",
    toast_injection_added: "Injection added successfully",
    toast_injection_updated: "Injection updated successfully",
    toast_injection_deleted: "Injection deleted successfully",
    toast_profile_updated: "Profile updated successfully!",
    permission_denied: "Permission denied: you don't have access to this action",
    forgot_password: "Forgot password? Sign out",
    forgot_password_link: "Forgot your password?",
    forgot_password_title: "Forgot Password?",
    forgot_password_prompt: "It seems you're having trouble. Do you want to recover your password via Telegram?",
    no_cancel: "No",
    yes_recover: "Yes",
    undo: "Undo",
    reset_password_title: "Reset Password",
    reset_password_desc: "Enter your email and we'll send you a reset link.",
    send_link: "Send Link",
    check_email: "Check your email for the reset link!",
    email_placeholder: "Email",
    magic_link_sent: "Magic link sent! Check your email to log in.",
    select_date: "Select Date",
    select_time: "Select Time",
    hours: "Hours",
    minutes: "Minutes",
    set_time: "Set Time",
    january: "January", february: "February", march: "March", april: "April", may: "May", june: "June",
    july: "July", august: "August", september: "September", october: "October", november: "November", december: "December",
    sun: "Su", mon: "Mo", tue: "Tu", wed: "We", thu: "Th", fri: "Fr", sat: "Sa",
    surgeries_today: "Surgeries Today",
    injections_due: "Injections Due",
    active_patients: "Active Patients",
    consultations: "Consultations",
    todays_operations: "Today's Operations",
    live_now: "Live Now",
    no_operations: "No Operations",
    view_floor_map: "View Floor Map",
    filter_all: "All",
    filter_operations: "Operations",
    filter_injections: "Injections",

    account_status: "Account Status",
    show: "Show",
    hide: "Hide",
    tomorrow: "Tomorrow",
    upcoming_patients: "Upcoming Patients",
    operation: "Operation",
    plasma_followups: "Plasma & Follow-ups",
    due_within_24h: "DUE WITHIN 24H",
    routine_followup: "Routine Follow-up",
    view_master_schedule: "View Master Schedule",
    registration_overview: "Overview of patient registration",
    overview: "Overview",
    upcoming_schedule: "Upcoming schedule",
    source_walkin: "Walk-in",
    source_referral: "Referral",
    schedule_for: "Schedule for",
    no_events_day: "No appointments scheduled",
    check_other_dates: "Check other dates on the calendar",
    patients_scheduled: "Patients Scheduled",
    view_all_schedule: "View Full Schedule",

    // Toasts
    success: "Success",
    copied_to_clipboard: "Copied to clipboard",
    toast_success_title: "Success",
    saving_patient_data: "Saving patient data...",
    uploading_large_image: "Uploading large image, please wait...",
    toast_error_title: "Error",
    toast_info_title: "Info",
    profile_updated_title: "Profile Updated",
    profile_updated_msg: "Your changes have been saved successfully.",
    patient_added_title: "Patient Added",
    patient_added_msg: "A new profile has been created in the database.",
    patient_updated_title: "Patient Updated",
    patient_updated_msg: "Patient profile saved successfully.",
    deleted_title: "Deleted",
    patient_deleted_msg: "Patient data has been completely removed.",
    injection_added_title: "Injection Added",
    injection_added_msg: "New procedure successfully added to schedule.",
    photo_added_title: "Photo Added",
    photo_added_msg: "New clinical photo has been successfully saved.",
    photo_deleted_title: "Photo Deleted",
    photo_deleted_msg: "Photo has been removed from gallery.",
    status_updated_title: "Status Updated",
    status_updated_msg: "Injection status has been successfully modified.",
    lead_deleted_msg: "Lead has been successfully removed.",
    toast_note_deleted: "Note deleted successfully.",
    toast_note_updated: "Note updated successfully.",
    toast_note_added: "New note added successfully.",
    reminder_set_title: "Reminder Set",
    reminder_set_msg: "Follow-up reminder has been scheduled.",
    reminder_deleted_msg: "Reminder removed.",
    status_frozen: "frozen",
    status_active_msg: "active",
    account_frozen_msg: "Account frozen successfully.",
    account_active_msg: "Account activated successfully.",
    broadcast_success: "Broadcast transmitted successfully.",
    account_created: "Account created successfully.",

    // Lock Screen
    security_check: "Security Check",
    remember_password: "Doctor, can you remember the password?",

    // Delete Modal
    delete_modal_headline: "Are we really saying goodbye?",
    delete_modal_subtext: "This action cannot be undone. All patient data, photos, and history will be permanently deleted.",
    confirm_remove_user: "Remove User?",
    confirm_remove_user_desc: "Are you sure you want to remove this user? They will no longer be able to login.",
    delete_modal_cancel: "No, keep it",
    delete_modal_confirm: "Yes, delete",
    delete_transaction_title: "Delete Transaction?",
    delete_transaction_desc: "Are you sure you want to delete this transaction?",

    // Empty States
    empty_state_peace: "Peace for now...",
    schedule_empty_title: "No Injections Yet",
    schedule_empty_mascot: "No injections scheduled yet. Let's plan the first recovery step!",
    add_first_injection: "Schedule First Injection",
    next_injection_tooltip: "Next Injection!",

    // Settings & Admin
    settings_desc: "Manage your profile, preferences, and security",
    account_id_label: "Account",
    preferences: "Preferences",
    notifications: "Notifications",
    no_notifications_yet: "No notifications yet",
    time_just_now: "Just now",
    time_minute_ago: "{m}m ago",
    time_hour_ago: "{h}h ago",
    app_appearance: "App Appearance",
    light_mode: "Light",
    security: "Security",
    sound_settings: "Sound Settings",
    enable_sound: "Enable Sound",
    sound_hint: "Play sound effects for notifications and actions.",
    two_factor: "Two-Factor Auth",
    verify_account_password: "Verify Account Password",
    sync_pin_hint: "Required to save the new PIN as your account password",
    logout_desc: "End your current session",
    admin_control_center: "Super Admin Control Center",
    admin_panel: "Admin Panel",
    god_mode: "God Mode Active",
    megaphone_title: "The Megaphone",
    megaphone_desc: "Broadcast an instant alert to every active user.",
    transmit: "Transmit",
    clear: "Clear",

    // Pagination
    pagination_showing: "Showing {start}-{end} of {total} patients",
    prev_page: "Previous",
    next_page: "Next",
    page_of: "Page {current} of {total}",

    // Validation
    validation_name_required: "Full name is required",
    validation_phone_required: "Phone number is required",
    validation_age_invalid: "Please enter a valid age (1-120)",
    validation_technique_required: "Please select a technique",
    validation_date_required: "Operation date is required",

    // Empty State
    empty_patient_list_title: "No Patients Found",
    empty_patient_list_desc: "It looks quiet here. Add a new patient to get started!",

    // Tour Guide
    tour_welcome_title: "Welcome, Doctor!",
    tour_welcome_desc: "I'm your Graft assistant. Let me show you around the dashboard.",
    tour_stats_desc: "Here you can track operation and injection statistics.",
    tour_add_btn_desc: "The most important button! Click here to add a new patient.",

    // Kanban
    status_new: "New",
    status_contacted: "Contacted",
    status_photos_sent: "Photos Sent",
    status_price_given: "Price Given",
    status_booked: "Operation",
    status_lost: "Cancelled",
    edit_lead: "Edit Lead",
    add_new_lead: "Add New Lead",

    // Filters
    filter_quick_filters: "Quick Filters:",
    filter_today_calls: "Today's Calls",
    filter_this_week: "This Week",
    filter_has_reminder: "Has Reminder",
    filter_source: "Source:",
    filter_clear_all: "Clear All",
    filter_source_instagram: "Instagram",
    filter_source_telegram: "Telegram",
    filter_source_walkin: "Walk-in",
    filter_source_referral: "Referral",

    // Note Status
    urgency: "Urgency",
    todo: "Todo",
    note: "Note",
    my_notes: "My Notes",
    new_note: "New Note",
    no_notes_found: "No notes found",
    no_patients_found: "No patients found",
    no_leads: "No leads",
    add_btn: "Add",
    get_login_code: "Get Login Code",
    login_with_email: "Login with Email",
    phone_label: "+998",
    otp_code_sent: "Enter the 6-digit code sent to your Telegram",
    change_phone: "Change Phone Number",
    note_title_placeholder: "Title (optional)",
    note_content_placeholder: "Note content...",
    view_patient_details: "View Patient Details",
    tier: "Tier",
    tier_regular: "Regular Patient",
    tier_pro: "Pro Patient (Bonus)",
    messages: "Messages",
    placeholder_type_message: "Type a message...",
    status_online: "Online",
    status_offline: "Offline",
    label_today: "Today",
    no_messages_yet: "No messages yet",
    load_more: "Load More",
    scheduled_for: "Scheduled for",
    no_scheduled_messages: "No scheduled messages",
    tab_chat: "Chat",
    tab_scheduled: "Scheduled",
    // LeadDetail
    lead_activity: "Activity",
    lead_created: "Lead created",
    add_note_placeholder: "Add a note...",
    source_label: "Source",
    source_instagram: "Instagram",
    source_telegram: "Telegram",
    overdue_reminder: "Overdue",
    upcoming_reminder: "Reminder",
    reminder: "Reminder",
    reminder_call_now: "Call Now",
    remind: "Remind",
    complete: "Complete",
    remind_result: "Result",
    added: "Added",
    set_lead_status: "Set Lead Status",
    just_now: "Just now",
    set_reminder: "Set Reminder",
    dont_forget_call: "Don't forget to call the customer",
    quick_select: "Quick Select",

    // Finance
    finance: "Finance",
    general_info: "General Info",
    finance_dashboard: "Finance Dashboard",
    finance_subtitle: "Track income, expenses, and profit",
    add_transaction: "Add Transaction",
    recent_transactions: "Recent Transactions",
    net_profit: "Net Profit",
    total_income: "Total Income",
    total_expenses: "Total Expenses",
    profitable: "Profitable",
    loss: "Loss",
    salary: "Salary",
    expense: "Expense",
    income: "Income",
    other: "Other",
    custom_category: "Custom Category",
    enter_category: "Enter category name...",
    surgery: "Surgery",
    consultation: "Consultation",
    rent: "Rent",
    equipment: "Equipment",
    add_payment: "Add Payment",
    save_payment: "Save Payment",
    marketing: "Marketing",
    food: "Food",
    utility: "Utility",
    tax: "Tax",
    tax_exp: "Tax/Expense",
    payment_received: "Payment Received",
    amount: "Amount",
    currency: "Currency",
    category: "Category",
    paid_so_far: "Paid So Far",
    completed: "Completed",
    no_payments_yet: "No Payments Yet",
    no_payments_desc: "Payment transactions will appear here once added.",
    remaining_balance: "Remaining",
    fully_paid: "Fully Paid",
    partially_paid: "Partially Paid",
    underpaid: "Underpaid",
    payment_progress: "Payment Progress",
    last_payment: "Last Payment",
    staff_member: "Staff Member",
    patient: "Patient",
    date_filter_all: "All Time",
    date_filter_month: "This Month",
    date_filter_week: "This Week",
    no_transactions_title: "No Transactions Yet",
    no_transactions_desc: "Start tracking your clinic's finances by adding your first transaction.",
    all_months: "All Months",
    this_month: "This Month",

    // Staff
    staff_management: "Staff Management",
    staff_subtitle: "Manage your team members and roles",
    add_staff: "Add Staff",
    search_staff: "Search by name or role...",
    edit_staff: "Edit Staff",
    add_new_staff: "Add New Staff",
    staff_modal_subtitle: "Fill in the details below to add a new team member.",
    no_staff_found: "No staff members found",
    add_first_staff: "Start by adding your first team member",
    upload_photo: "Upload Photo",
    role: "Role",

    save_staff: "Save",
    update_staff: "Update Staff",
    notes_placeholder: "Think different...",
    role_doctor: "Doctor",
    role_assistant: "Assistant",
    role_receptionist: "Receptionist",
    role_nurse: "Nurse",
    role_cleaner: "Cleaner",
    role_admin: "Admin",
    role_other: "Other",
    status_on_leave: "On Leave",
    status_terminated: "Terminated",
    staff_added_title: "Staff Added",
    staff_added_msg: "New staff member has been successfully added.",
    staff_updated_title: "Staff Updated",
    staff_updated_msg: "Staff member details have been updated.",
    staff_deleted: "Staff member has been removed.",
    transaction_history: "Transaction History",
    payment_history: "Payment History",
    payment: "Payment",
    paid: "PAID",
    no_payments_found: "No payments found",
    start_payments: "Start tracking payments for this staff member.",
    staff_delete_popup_title: "Delete Staff Member?",
    staff_delete_popup_desc: "Are you sure you want to remove this staff member? This action cannot be undone.",

    // Transactions
    search_transactions: "Search transactions...",
    transactions: "Transactions",
    from_date: "From Date",
    to_date: "To Date",
    all_categories: "All Categories",
    time_range: "Time Range",
    transaction_type: "Transaction Type",
    all_types: "All Types",
    income_only: "Income Only",
    expense_only: "Expense Only",
    all_time: "All Time",
    fill_details: "Fill in the details below",
    transaction_details: "Transaction Details",
    income_distribution: "Income Distribution (Splits)",
    add_split: "+ Add Split",
    splits_empty_state: "Add splits to distribute income (e.g. tax, salary)",
    net_income: "Net Income",
    gross_income: "Gross Income",
    finance_overview: "Financial constraints and analytics",
    review_analytics: "Review Analytics",
    income_statistics: "Income and expense statistics",
    recent: "Recent",
    view_all: "View All",
    filter_by_category: "Filter by Category",
    no_transactions_found: "No transactions found",
    adjust_filters_hint: "Try adjusting your filters or search terms to find what you're looking for.",
    clear_filters: "Clear all filters",
    staff: "Staff",
    search_patients: "Search patients...",

    transaction_deleted: "Deleted",
    transaction_deleted_msg: "Transaction successfully deleted",
    error_deleting: "Error deleting",
    restored: "Restored",
    restored_msg: "Transaction successfully restored",
    select_patient: "Select Patient",
    enter_custom_category: "Enter custom category...",
    add_note_details: "Add a note details...",
    confirm_expense: "Confirm Expense",
    confirm_income: "Confirm Income",
    description: "Description",
    add_description: "Add a description...",
    expense_note_placeholder: "Write about the expense...",
    select_staff: "Select Staff",
    staff_member_label: "Staff",
    pay_salary: "Pay Salary",
    pay_all_salaries: "Pay All Salaries",
    salary_paid: "Salary Paid",
    salary_paid_msg: "Salary payment recorded successfully",
    enter_amount: "Enter amount",
    salary_payment_desc: "Salary payment",
    salary_payment: "Salary Payment",
    records: "records",
    split_from: "[Split] ",
    distribution: "Distribution",
    clinic_remainder: "Clinic Remainder",
    split: "Split",
    salary_split: "Salary",
    step_title: "Step Title",
    step_title_ph: "e.g. Extraction Phase",
    doctor_staff: "Doctor / Staff",
    operation_active: "Operation Active",
    stop: "Stop",
    operation_successful: "Operation Successful",
    all_phases_completed: "All phases have been completed.",
    reset_tracker: "Reset Tracker",
    reset_tracker_desc: "Are you sure you want to reset the operation and clear all progress? This action cannot be undone.",
    reset: "Reset",
    skip: "Skip",
    operation_progress: "Operation Progress",
    no_operation_steps: "No operation steps defined",
    add_phases_ph: "Add phases e.g. Anesthesia, Extraction, Implantation",
    hours_short: "Hrs",
    start_operation: "Start Operation",
    add: "Add",



  },
  uz: {
    loading: "Yuklanmoqda...",
    loading_pleasewait: "Barchasi nazorat ostida, ozgina kuting...",
    no_chat_selected: "Suhbat tanlanmagan",
    select_patient_msg: "Xabarlar tarixini ko‘rish uchun chap menyudan bemorni tanlang.",
    // Navigation
    management: "Boshqaruv",
    files: "Fayllar",
    my_files: "Mening Fayllarim",
    tasks_folder: "Vazifalar",
    notes_folder: "Eslatmalar",
    step: "Qadam",
    done: "Bajarildi",
    add_note_prompt: "Yangi eslatma qo'shing",
    search_files: "Fayllarni qidirish...",
    roles: "Rollar",
    roles_management: "Rollarni boshqarish",
    add_user: "Foydalanuvchi Qo'shish",
    search_users: "Foydalanuvchilarni qidirish...",
    no_results_found: "Mos keladigan foydalanuvchilar topilmadi",
    no_users_found: "Foydalanuvchilar topilmadi",
    // Roles Specific
    edit_user: "Foydalanuvchini Tahrirlash",
    add_user_title: "Yangi Foydalanuvchi Qo'shish",
    new_password_optional: "Yangi Parol (Ixtiyoriy)",
    leave_blank_password: "O'zgartirmaslik uchun bo'sh qoldiring",
    set_login_password: "Kirish parolini o'rnating",
    role_permission: "Rol Ruxsatnomasi",
    viewer_role: "Kuzatuvchi (Viewer)",
    read_only_access: "Faqat ko'rish ruxsati",
    call_operator_role: "Operator",
    leads_only_access: "Faqat mijozlar bilan ishlash",
    nurse_role: "Hamshira",
    patients_only_access: "Faqat bemorlar bilan ishlash",
    create_account: "Hisob Yaratish",
    save_changes: "O'zgarishlarni Saqlash",
    remove: "O'chirib tashlash",
    only_admins_roles: "Faqat Adminlar rollarni boshqarishi mumkin.",
    roles_management_subtitle: "Kuzatuvchilar va Operatorlar ruxsatini boshqarish.",

    // Roles Toasts
    toast_password_reset_note: "Eslatma: Parol yangilanishi qayta kirishni yoki admin tomonidan tiklashni talab qiladi.",
    toast_user_added: "Foydalanuvchi muvaffaqiyatli qo'shildi:",
    toast_user_updated: "Foydalanuvchi ma'lumotlari saqlandi.",
    toast_user_removed: "Foydalanuvchi o'chirildi",
    toast_access_revoked: "Kirish huquqi bekor qilindi.",
    toast_remove_failed: "Foydalanuvchini o'chirishda xatolik.",
    toast_phone_exists: "Bu telefon raqami allaqachon ro'yxatdan o'tgan.",
    validation_pin_error: "Parol aniq 6 ta raqamdan iborat bo'lishi kerak.",
    set_login_password_placeholder: "6 xonali Login PIN o'rnating",

    dashboard: "Boshqaruv paneli",
    patients: "Bemorlar",
    new_patient: "Yangi Bemor",
    help: "Yordam",
    settings: "Sozlamalar",
    logout: "Chiqish",
    search: "Qidirish...",
    dr_name: "Akaunt Egasi",
    total_patients: "Jami Bemorlar",
    total_revenue: "Jami Tushum",
    new_patients_stat: "Yangi Bemorlar",
    total_appointments: "Jami Uchrashuvlar",
    requests: "So'rovlar",
    leads: "Mijozlar",
    last_month: "O'tgan oy",
    patients_stats: "Bemorlar Statistikasi",
    monthly: "Oylik",
    yearly: "Yillik",
    weekly: "Haftalik",
    todays_appointments: "Bugungi Uchrashuvlar",
    see_all: "Hammasini ko'rish",
    patient_directory: "Bemorlar Ro'yxati",
    total: "Jami",
    active: "Faol",
    name: "Ism",
    operation_date: "Operatsiya Sanasi",
    next_injection: "Keyingi Inyeksiya",
    status: "Holat",
    action: "Amal",
    none_scheduled: "Rejalashtirilmagan",
    view: "Ko'rish",
    back_to_list: "Ro'yxatga qaytish",
    edit: "Tahrirlash",
    age: "Yosh",
    gender: "Jins",
    phone: "Telefon",
    email: "Email Manzil",
    grafts: "Graftlar Soni",
    technique: "Operatsiya turi",
    select_tech: "Turini tanlang",
    tech: "Turi",
    transplant_hair: "Soch",
    transplant_eyebrow: "Qosh",
    transplant_beard: "Soqol",
    before_operation: "Operatsiyadan oldin",
    before_media: "Oldindan media",
    upload_photo_video: "Rasm/video yuklash",
    view_photo: "Rasmni ko'rish",
    play_video: "Videoni ko'rish",
    progress: "Jarayon",
    add_photo: "Rasm qo'shish",
    add_media: "Media qo'shish",
    injection_schedule: "Plazma Inyeksiya Jadvali",
    medically_verified: "Tibbiy Tasdiqlangan",
    injection: "Inyeksiya",
    mark_done: "Bajarildi",
    mark_missed: "O'tkazildi",
    new_patient_reg: "Mehmon be'mor",
    edit_patient_title: "Bemor Profilini Tahrirlash",
    full_name: "To'liq Ism",
    first_name: "Ism",
    last_name: "Familiya",
    phone_number: "Telefon Raqami",
    save_patient: "Bemorni Saqlash",
    saving: "Saqlanmoqda...",
    uploading: "Yuklanmoqda...",
    cancel: "Bekor qilish",
    click_upload: "Rasm yuklash",
    patient_list: "Bemorlar Ro'yxati",
    details: "Tafsilotlar",
    add_new_patient: "Yangi Bemor Qo'shish",
    journey_of_recovery: "Tiklanish sayohati",
    today: "Bugun",
    schedule: "Jadval",
    upcoming: "Kelgusi",
    years: "Yosh",
    no_image: "Rasm yo'q",
    no_progress: "Hozircha jarayon rasmlari yo'q.",
    no_upcoming: "Kutilayotgan inyeksiyalar yo'q.",
    plasma_injection: "Plazma Inyeksiyasi",
    status_active: "Faol",
    status_recovered: "Tuzalgan",
    status_observation: "Kuzatuvda",
    status_scheduled: "Rejalashtirilgan",
    status_completed: "Bajarildi",
    status_missed: "O'tkazildi",
    status_cancelled: "Bekor qilindi",
    gender_male: "Erkak",
    gender_female: "Ayol",
    gender_other: "Boshqa",
    add_injection: "Inyeksiya Belgilash",
    edit_injection: "Inyeksiyani Tahrirlash",
    date: "Sana",
    notes: "Izohlar",
    save: "Saqlash",
    confirm_logout_title: "Chiqish?",
    confirm_logout_desc: "Tizimdan chiqmoqchimisiz?",
    keep_logged_in: "Tizimda qolish",
    photo_label_title: "Rasm Vaqti",
    time_since_op: "Operatsiyadan o'tgan vaqt",
    pinned_message: "📌 Qadalgan xabar",
    reply_to: "Javob berish",
    value: "Qiymat",
    unit: "Birlik",
    days: "Kun",
    weeks: "Hafta",
    months: "Oy",
    enter_notes: "Izoh qoldiring...",
    delete: "O'chirish",
    reply: "Javob",
    copy: "Nusxalash",
    pin: "Qadash",
    unpin: "Yechish",
    confirm_delete: "Ushbu inyeksiyani o'chirmoqchimisiz?",
    delete_modal_title: "Ishonchingiz komilmi?",
    delete_warning: "Ushbu amalni ortga qaytarib bo'lmaydi. Ushbu seansni butunlay o'chirib tashlashga ishonchingiz komilmi?",
    delete_photo_title: "Ishonchingiz komilmi?",
    delete_photo_desc: "Ushbu rasm bemorning jarayon tarixidan butunlay olib tashlanadi. Ishonchingiz komilmi?",
    undo: "Qaytarish",
    confirm: "Tasdiqlash",
    yes: "Ha",
    no: "Yo'q",
    login_welcome: "Xush kelibsiz",
    login_subtitle: "Iltimos, kirish kodini kiriting",
    enter_password: "Parolni kiriting",
    login_btn: "Kirish",
    wrong_password: "Parol noto'g'ri, iltimos qayta urinib ko'ring.",
    access_restricted: "Kirish Cheklangan",
    edit_profile: "Profilni Tahrirlash",
    current_password: "Joriy Parol",
    new_password: "Yangi Parol",
    password_hint: "6 xonali PIN kod yarating",
    optional_change: "(ixtiyoriy - faqat o'zgartirish uchun)",
    profile_photo: "Profil Rasmi",
    before_photo: "Klinik Rasm (Oldin)",
    personal_info: "Shaxsiy Ma'lumotlar",
    medical_details: "Tibbiy Tafsilotlar",
    enter_patient_details: "Quyida bemor tafsilotlarini kiriting",
    upload_image: "Rasm yuklash",
    lock_app: "Ilovani Qulflash",
    app_locked: "Ilova Qulflangan",
    enter_pin: "PIN kodni kiriting",
    unlock: "Ochish",
    enable_lock: "Qulf ekranini yoqish",
    lock_hint: "Xavfsizlik uchun yon panelga qulf tugmasini qo'shadi.",
    security_settings: "Xavfsizlik Sozlamalari",
    edit_patient: "Tahrirlash",
    delete_patient: "O'chirish",
    delete_patient_confirm: "Haqiqatan ham ushbu bemor profilini o'chirmoqchimisiz? Barcha ma'lumotlar, shu jumladan rasmlar va tarix butunlay o'chiriladi.",
    login_phone: "Telefon Raqami",
    login_password: "Parol",
    login_signin: "Kirish",
    login_title: "Klinika hisobingizga kiring",
    delete_patient_title: "Bemorni o'chirib tashlaysizmi?",
    danger_zone: "Xavfli Hudud",
    login_no_account: "Hisobingiz bo'lmasa, administratoringizga murojaat qiling",
    login_error_no_account: "Bu telefon raqami bilan hisob topilmadi",
    login_error_invalid_password: "Parol noto'g'ri",
    login_error_disabled: "Bu hisob o'chirilgan",
    login_error_generic: "Xatolik yuz berdi. Iltimos, qayta urinib ko'ring.",
    login_banned_msg: "Sizning hisobingiz bloklangan. Iltimos, administrator bilan bog'laning.",
    schedule_message_title: "Xabarni rejalashtirish",
    schedule_today: "Bugun",
    schedule_tomorrow: "Ertaga",
    schedule_send_today: "Yuborish Bugun soat",
    schedule_send_tomorrow: "Yuborish Ertaga soat",
    schedule_send_date: "Yuborish",
    schedule_at: "soat",
    pick_date: "Sana tanlash",
    back: "Orqaga",
    alert_future_time: "Iltimos, kelajakdagi vaqtni tanlang.",
    login_frozen_msg: "Hisobingiz vaqtincha muzlatilgan. Iltimos, yordam xizmati bilan bog'laning.",
    select_language: "Til",
    toast_profile_saved: "Profil muvaffaqiyatli saqlandi!",
    toast_save_failed: "Saqlashda xatolik",
    toast_upload_failed: "Rasm yuklashda xatolik",
    toast_password_short: "Parol kamida 6 ta belgidan iborat bo'lishi kerak",
    toast_no_session: "Faol seans yo'q - iltimos, chiqib qayta kiring",
    toast_patient_added: "Bemor muvaffaqiyatli qo'shildi",
    toast_patient_updated: "Bemor ma'lumotlari yangilandi",
    toast_patient_deleted: "Bemor muvaffaqiyatli o'chirildi",
    toast_delete_failed: "Bemorni o'chirishda xatolik",
    toast_photo_added: "Rasm muvaffaqiyatli qo'shildi",
    toast_photo_deleted: "Rasm muvaffaqiyatli o'chirildi",
    toast_injection_added: "Inyeksiya muvaffaqiyatli qo'shildi",
    toast_injection_updated: "Inyeksiya muvaffaqiyatli yangilandi",
    toast_injection_deleted: "Inyeksiya muvaffaqiyatli o'chirildi",
    toast_profile_updated: "Profil muvaffaqiyatli yangilandi!",
    permission_denied: "Ruxsat etilmadi: ushbu amalni bajarishga huquqingiz yo'q",
    forgot_password: "Parolni unutdingizmi? Chiqish",
    forgot_password_link: "Parolingizni unutdingizmi?",
    forgot_password_title: "Parolni unutdingizmi?",
    forgot_password_prompt: "Kirishda muammo bormi? Parolni Telegram orqali tiklashni xohlaysizmi?",
    no_cancel: "Yo'q",
    yes_recover: "Ha",
    reset_password_title: "Parolni Tiklash",
    reset_password_desc: "Emailingizni kiriting, sizga qayta tiklash havolasini yuboramiz.",
    send_link: "Havola Yuborish",
    check_email: "Qayta tiklash havolasi uchun emailingizni tekshiring!",
    email_placeholder: "Email",
    forgot_password_confirm: "Parolni tiklash uchun tizimdan chiqishingiz kerak. Ma'lumotlaringiz xavfsiz saqlanadi.",
    magic_link_sent: "Sehrli havola yuborildi! Kirish uchun emailingizni tekshiring.",
    select_date: "Sanani tanlang",
    select_time: "Vaqtni tanlang",
    hours: "Soat",
    minutes: "Daqiqa",
    set_time: "Vaqtni belgilash",
    january: "Yanvar", february: "Fevral", march: "Mart", april: "Aprel", may: "May", june: "Iyun",
    july: "Iyul", august: "Avgust", september: "Sentyabr", october: "Oktyabr", november: "Noyabr", december: "Dekabr",
    sun: "Yak", mon: "Du", tue: "Se", wed: "Cho", thu: "Pay", fri: "Ju", sat: "Sha",
    surgeries_today: "Bugungi Operatsiyalar",
    injections_due: "Kutilayotgan Inyeksiyalar",
    active_patients: "Faol Bemorlar",
    consultations: "Konsultatsiyalar",
    todays_operations: "Bugungi Operatsiyalar",
    live_now: "Hozir Amalda",
    no_operations: "Operatsiyalar Yo'q",
    view_floor_map: "Xaritani Ko'rish",
    filter_all: "Barchasi",
    filter_operations: "Operatsiyalar",
    filter_injections: "Inyeksiyalar",

    current_plan: "Joriy Tarif",
    show: "Ko'rsatish",
    hide: "Yashirish",
    tomorrow: "Ertaga",
    plan_details: "Tarif Tafsilotlari",
    valid_until: "OBUNA TUGASH SANASI",
    status_not_paid: "To'lov Talab Qilinadi",
    status_trial: "Sinov Muddatida",
    transaction_history: "To'lovlar Tarixi",
    no_transactions: "Hozircha tranzaksiyalar yo'q.",
    payment_gateway: "O'zbekiston Xavfsiz To'lov Tizimi",
    subscription_fee: "Obuna To'lovi",
    pay_subscription: "Obuna uchun to'lash",


    feature_full_access: "Bemorlar ma'lumotlariga to'liq kirish",
    feature_realtime: "Ma'lumotlarni real vaqtda sinxronlash",
    feature_backups: "Avtomatik zaxira nusxalash va xavfsizlik",
    feature_sync: "Cheksiz qurilmalararo sinxronlash",
    upcoming_patients: "Kutilayotgan bemorlar",
    operation: "Operatsiya",
    plasma_followups: "Plazma va nazorat",
    due_within_24h: "24 SOAT ICHIDA",
    routine_followup: "Muntazam nazorat",
    view_master_schedule: "Asosiy jadvalni ko'rish",
    registration_overview: "Bemorlarni ro'yxatga olish sharhi",
    overview: "Umumiy ko'rinish",
    upcoming_schedule: "Kelgusi jadval",
    account_status: "Hisob Holati",
    source_walkin: "O'zi kelgan",
    source_referral: "Tavsiya",
    schedule_for: "Jadval:",
    no_events_day: "Bugun uchun qabul rejalashtirilmagan",
    check_other_dates: "Taqvimning boshqa kunlarini tekshiring",
    patients_scheduled: "nafar bemor rejalashtirilgan",
    view_all_schedule: "Barcha jadvalni ko'rish",
    prev_page: "Oldingi",
    next_page: "Keyingi",
    page_of: "Sahifa {current} / {total}",

    // Toasts
    toast_success_title: "Sinxronizatsiya a'lo!",
    saving_patient_data: "Bemor ma'lumotlari saqlanmoqda...",
    uploading_large_image: "Katta hajmdagi rasm yuklanmoqda, iltimos kuting...",
    toast_error_title: "Xatolik yuz berdi",
    toast_info_title: "Bildirishnoma",
    profile_updated_title: "Profil yangilandi",
    profile_updated_msg: "Tahrirlangan ma'lumotlar muvaffaqiyatli saqlandi.",
    patient_added_title: "Bemor qo'shildi",
    patient_added_msg: "Yangi profil bazada muvaffaqiyatli yaratildi.",
    patient_updated_title: "Bemor Yangilandi",
    patient_updated_msg: "Bemor ma'lumotlari muvaffaqiyatli saqlandi.",
    deleted_title: "O'chirildi",
    patient_deleted_msg: "Bemor ma'lumotlari butunlay olib tashlandi.",
    injection_added_title: "Inyeksiya qo'shildi",
    injection_added_msg: "Yangi muolaja jadvalga muvaffaqiyatli kiritildi.",
    photo_added_title: "Rasm qo'shildi",
    photo_added_msg: "Bemorning yangi jarayon fotosurati saqlandi.",
    photo_deleted_title: "Rasm o'chirildi",
    photo_deleted_msg: "Fotosurat galereyadan muvaffaqiyatli olib tashlandi.",
    injection_updated_title: "Inyeksiya yangilandi",
    injection_updated_msg: "O'zgarishlar jadvalga muvaffaqiyatli saqlandi.",
    status_updated_title: "Holat yangilandi",
    status_updated_msg: "Inyeksiya holati muvaffaqiyatli o'zgartirildi.",
    lead_deleted_msg: "Mijoz muvaffaqiyatli o'chirildi.",
    toast_note_deleted: "Eslatma muvaffaqiyatli o'chirildi.",
    toast_note_updated: "Eslatma muvaffaqiyatli yangilandi.",
    toast_note_added: "Yangi eslatma muvaffaqiyatli qo'shildi.",
    reminder_set_title: "Eslatma belgilandi",
    reminder_set_msg: "Mijoz bilan bog'lanish eslatmasi saqlandi.",
    reminder_deleted_msg: "Eslatma o'chirildi.",
    status_frozen: "muzlatildi",
    status_active_msg: "faollashtirildi",
    account_frozen_msg: "Hisob muvaffaqiyatli muzlatildi.",
    account_active_msg: "Hisob muvaffaqiyatli faollashtirildi.",
    broadcast_success: "Xabar muvaffaqiyatli yuborildi.",
    account_created: "Hisob muvaffaqiyatli yaratildi.",
    banned_title: "Akkount Bloklandi",
    banned_desc: "Xavfsizlik qoidalarini buzganlik sababli sizning hisobingiz bloklandi. Iltimos, qayta tiklash uchun administrator bilan bog'laning.",
    banned_contact_btn: "Admin bilan bog'lanish",
    banned_logout: "Chiqish",
    // Lock Screen
    security_check: "Xavfsizlik Tekshiruvi",
    remember_password: "Doktor, parolni eslay olasizmi?",

    // Delete Modal
    delete_modal_headline: "Rostdan ham xayrlashamizmi?",
    delete_modal_subtext: "Bu amalni ortga qaytarib bo'lmaydi. Bemorning barcha ma'lumotlari, rasmlari va tarixi butunlay o'chiriladi.",
    confirm_remove_user: "Foydalanuvchini o'chirish?",
    confirm_remove_user_desc: "Haqiqatan ham ushbu foydalanuvchini o'chirishni xohlaysizmi? Ular endi tizimga kira olmaydilar.",
    delete_modal_cancel: "Yo'q, qolsin",
    delete_modal_confirm: "Ha, o'chirilsin",
    delete_transaction_title: "Tranzaksiyani o'chirish?",
    delete_transaction_desc: "Ushbu tranzaksiyani o'chirmoqchimisiz?",

    // Empty States
    empty_state_peace: "Hozircha tinchlik...",
    schedule_empty_title: "Hali inyeksiyalar yo'q",
    schedule_empty_mascot: "Hozircha inyeksiyalar belgilanmagan. Tiklanishning birinchi bosqichini rejalashtiramizmi?",
    add_first_injection: "Birinchi inyeksiyani belgilash",
    next_injection_tooltip: "Navbatdagi ukol!",

    // Settings & Admin
    settings_desc: "Profil, afzalliklar va xavfsizlikni boshqarish",
    account_id_label: "Hisob",
    preferences: "Afzalliklar",
    notifications: "Bildirishnomalar",
    no_notifications_yet: "Hozircha hech qanday bildirishnoma yo'q",
    time_just_now: "Hozirgina",
    time_minute_ago: "{m} m avval",
    time_hour_ago: "{h} s avval",
    app_appearance: "Ilova ko'rinishi",
    light_mode: "Yorug'",
    security: "Xavfsizlik",
    sound_settings: "Ovoz Sozlamalari",
    enable_sound: "Ovozni Yoqish",
    sound_hint: "Bildirishnoma va harakatlar uchun ovoz effektlari.",
    two_factor: "Ikki Bosqichli Himoya",
    verify_account_password: "Hisob parolini tasdiqlash",
    sync_pin_hint: "Yangi PINni hisob paroli sifatida saqlash uchun talab qilinadi",
    logout_desc: "Tizimdan chiqish",
    admin_control_center: "Super Admin Markazi",
    admin_panel: "Admin Paneli",
    god_mode: "Xudo rejimi faol",
    megaphone_title: "Megafon",
    megaphone_desc: "Barcha faol foydalanuvchilarga xabar yuborish.",
    transmit: "Yuborish",
    clear: "Tozalash",

    // Pagination
    pagination_showing: "Jami {total} bemordan {start}-{end} ko'rsatilmoqda",

    // Validation
    validation_name_required: "To'liq ism kiritilishi shart",
    validation_phone_required: "Telefon raqami kiritilishi shart",
    validation_age_invalid: "Iltimos, to'g'ri yoshni kiriting (1-120)",
    validation_technique_required: "Iltimos, operatsiya turini tanlang",
    validation_date_required: "Operatsiya sanasi kiritilishi shart",

    // Kanban
    status_new: "Yangi",
    status_contacted: "Bog'lanildi",
    status_photos_sent: "Rasm Yuborildi",
    status_price_given: "Narx Berildi",
    status_booked: "Operatsiya",
    status_lost: "Bekor Qilingan",
    edit_lead: "Mijozni Tahrirlash",
    add_new_lead: "Yangi Mijoz Qo'shish",

    // Filters
    filter_quick_filters: "Tezkor filtrlar:",
    filter_today_calls: "Bugungi qo'ng'iroqlar",
    filter_this_week: "Bu hafta",
    filter_has_reminder: "Eslatmasi bor",
    filter_source: "Manba:",
    filter_clear_all: "Hammasini tozalash",
    filter_source_instagram: "Instagram",
    filter_source_telegram: "Telegram",
    filter_source_walkin: "O'zi kelgan",
    filter_source_referral: "Tavsiya",

    // Transactions
    search_transactions: "Tranzaksiyalarni qidirish...",
    transactions: "Tranzaksiyalar",
    from_date: "Sanadan",
    to_date: "Sanagacha",
    all_categories: "Barcha Kategoriyalar",
    time_range: "Vaqt Oralig‘i",
    transaction_type: "O‘tkazma Turi",
    all_types: "Barcha Turlar",
    income_only: "Faqat Kirim",
    expense_only: "Faqat Chiqim",
    all_time: "Barcha vaqtlar",
    fill_details: "Quyidagi ma'lumotlarni to'ldiring",
    transaction_details: "Tranzaksiya Tafsilotlari",
    income_distribution: "Daromad Taqsimoti (Bo'linmalar)",
    add_split: "+ Bo'linma Qo'shish",
    splits_empty_state: "Daromadni taqsimlash uchun bo'linmalar qo'shing (masalan, soliq, maosh)",
    net_income: "Sof Daromad",
    gross_income: "Yalpi Daromad",
    review_analytics: "Tahlilni Ko'rish",
    income_statistics: "Kirim va chiqim statistikasi",
    recent: "So'nggi",
    view_all: "Hammasini ko'rish",
    filter_by_category: "Kategoriya bo'yicha",
    no_transactions_found: "Tranzaksiyalar topilmadi",
    adjust_filters_hint: "Filtrlarni yoki qidiruv so'zlarini o'zgartirib ko'ring.",
    clear_filters: "Filtrlarni tozalash",
    staff: "Xodimlar",
    search_patients: "Bemorlarni qidirish...",





    // Empty State
    empty_patient_list_title: "Hozircha Bemorlar Yo'q",
    empty_patient_list_desc: "Bu yer tinch ko'rinadi. Ishni boshlash uchun yangi bemor qo'shing!",

    // Tour Guide
    tour_welcome_title: "Assalomu alaykum, Doktor!",
    tour_welcome_desc: "Men Graft yordamchisiman. Keling, sizga ish stolini ko'rsataman.",
    tour_stats_desc: "Bu yerda operatsiya va inyeksiyalar statistikasini kuzatib borasiz.",
    tour_add_btn_desc: "Eng muhim tugma! Yangi bemor qo'shish uchun shu yerni bosing.",

    // Note Status
    urgency: "Shoshilinch",
    todo: "Vazifa",
    note: "Eslatma",
    my_notes: "Eslatmalarim",
    new_note: "Yangi Eslatma",
    no_notes_found: "Eslatmalar topilmadi",
    no_patients_found: "Bemorlar topilmadi",

    // Finance
    finance: "Moliya",
    general_info: "Umumiy Ma'lumot",
    finance_dashboard: "Moliya Paneli",
    finance_filter_all: "Barchasi",
    finance_filter_month: "Shu Oy",
    finance_filter_week: "Shu Hafta",
    finance_overview: "Moliyaviy Ko'rsatkichlar",
    finance_subtitle: "Daromad, xarajatlar va foydani kuzatish",
    add_transaction: "Tranzaksiya Qo'shish",
    recent_transactions: "So'nggi Tranzaksiyalar",
    net_profit: "Sof Foyda",
    total_income: "Jami Daromad",
    total_expenses: "Jami Xarajatlar",
    profitable: "Foydali",
    loss: "Zarar",
    salary: "Ish haqi",
    expense: "Xarajat",
    income: "Kirim",
    other: "Boshqa",
    custom_category: "Boshqa Kategoriya",
    enter_category: "Kategoriya nomini kiriting...",
    surgery: "Operatsiya",
    consultation: "Konsultatsiya",
    rent: "Ijara",
    equipment: "Jihozlar",
    marketing: "Marketing",
    food: "Oziq-ovqat",
    utility: "Kommunal",
    tax: "Soliq",
    tax_exp: "Soliq/Xarajat",
    add_payment: "To'lov Qo'shish",
    save_payment: "To'lovni Saqlash",
    payment_received: "To'lov Qabul Qilindi",
    amount: "Miqdor",
    currency: "Valyuta",
    category: "Kategoriya",
    paid_so_far: "Hozircha To'landi",
    completed: "Bajarildi",
    no_payments_yet: "To'lovlar Hali Yo'q",
    no_payments_desc: "To'lov operatsiyalari qo'shilganda shu yerda ko'rinadi.",
    total_paid: "Jami To'landi",
    remaining_balance: "Qoldiq",
    fully_paid: "To'liq To'langan",
    partially_paid: "Qisman To'langan",
    underpaid: "Kam To'langan",
    payment_progress: "To'lov Jarayoni",
    last_payment: "Oxirgi To'lov",
    staff_member: "Xodim",
    patient: "Bemor",
    date_filter_all: "Barchasi",
    date_filter_month: "Shu Oy",
    date_filter_week: "Shu Hafta",
    no_transactions_title: "Tranzaksiyalar Yo'q",
    no_transactions_desc: "Klinika moliyasini kuzatishni boshlash uchun birinchi tranzaksiyani qo'shing.",
    all_months: "Barcha oylar",
    this_month: "Shu oy",

    transaction_deleted: "O'chirildi",
    transaction_deleted_msg: "Tranzaksiya muvaffaqiyatli o'chirildi",
    error_deleting: "O'chirishda xatolik",
    restored: "Tiklandi",
    restored_msg: "Tranzaksiya muvaffaqiyatli tiklandi",

    // Staff
    staff_management: "Xodimlar Boshqaruvi",
    staff_subtitle: "Jamoa a'zolari va rollarini boshqarish",
    add_staff: "Xodim Qo'shish",
    search_staff: "Ism yoki rol bo'yicha qidirish...",
    edit_staff: "Xodimni Tahrirlash",
    add_new_staff: "Yangi Xodim Qo'shish",
    staff_modal_subtitle: "Yangi jamoa a'zosini qo'shish uchun quyidagi ma'lumotlarni to'ldiring.",
    no_staff_found: "Hech qanday xodim topilmadi",
    add_first_staff: "Yangi xodim qo'shish orqali boshlang",
    upload_photo: "Rasm Yuklash",
    role: "Rol",

    save_staff: "Saqlash",
    update_staff: "Xodimni yangilash",
    notes_placeholder: "O'zgacha fikrlang...",
    role_doctor: "Shifokor",
    role_assistant: "Assistent",
    role_receptionist: "Retsepsionist",
    role_nurse: "Hamshira",
    role_cleaner: "Farrosh",
    role_admin: "Admin",
    role_other: "Boshqa",
    status_on_leave: "Dam olishda",
    status_terminated: "Bo'shatilgan",
    staff_added_title: "Xodim Qo'shildi",
    staff_added_msg: "Yangi xodim muvaffaqiyatli qo'shildi.",
    staff_updated_title: "Xodim Yangilandi",
    staff_updated_msg: "Xodim ma'lumotlari yangilandi.",
    staff_deleted: "Xodim o'chirildi.",
    no_leads: "Murojaatlar yo'q",
    add_btn: "Qo'shish",
    get_login_code: "Kirish Kodini Olish",
    login_with_email: "Email orqali kirish",
    phone_label: "+998",
    otp_code_sent: "6 xonali kod Telegram orqali yuborildi",
    change_phone: "Raqamni o'zgartirish",
    note_title_placeholder: "Sarlavha (ixtiyoriy)",
    note_content_placeholder: "Eslatma matni...",
    view_patient_details: "Bemor Tafsilotlarini Ko'rish",
    tier: "Daraja",
    tier_regular: "Oddiy Bemor",
    tier_pro: "Pro Bemor (Bonus)",
    messages: "Xabarlar",
    placeholder_type_message: "Xabar yozing...",
    status_online: "Online",
    status_offline: "Offline",
    label_today: "Bugun",
    no_messages_yet: "Hozircha xabarlar yo'q",
    load_more: "Yana yuklash",
    scheduled_for: "Rejalashtirilgan",
    salary_payment: "Oylik to'lov",
    records: "ta yozuv",
    split_from: "[Bo'linma] ",
    no_scheduled_messages: "Rejalashtirilgan xabarlar yo'q",
    tab_chat: "Suhbat",
    tab_scheduled: "Rejalashtirilgan",
    // LeadDetail
    lead_activity: "Faoliyat",
    lead_created: "Mijoz yaratildi",
    add_note_placeholder: "Izoh qo'shish...",
    source_label: "Manba",
    source_instagram: "Instagram",
    source_telegram: "Telegram",
    overdue_reminder: "Muddati o'tgan",
    upcoming_reminder: "Eslatma",
    reminder: "Eslatma",
    reminder_call_now: "Qo'ng'iroq qilish",
    remind: "Eslatish",
    complete: "Bajarish",
    remind_result: "Natija",
    added: "Qo'shildi",
    set_lead_status: "Statusni o'zgartirish",
    just_now: "Hozirgi",
    set_reminder: "Eslatma o'rnatish",
    dont_forget_call: "MIJOZGA QO'NG'IROQ QILISHNI UNUTMANG",
    quick_select: "TEZ TANLASH",
    // Staff Missing Keys
    payment_history: "To'lovlar Tarixi",
    payment: "To'lov",
    paid: "TO'LANGAN",
    no_payments_found: "To'lovlar topilmadi",
    start_payments: "Ushbu xodim uchun to'lovlarni kuzatishni boshlang.",
    staff_delete_popup_title: "Xodimni o'chirish?",
    staff_delete_popup_desc: "Haqiqatan ham ushbu xodimni o'chirib tashlamoqchimisiz? Bu amalni ortga qaytarib bo'lmaydi.",
    // Finance Missing Keys
    confirm_income: "Kirimni Tasdiqlash",
    confirm_expense: "Chiqimni Tasdiqlash",
    description: "Tavsif",
    add_description: "Izoh qo'shing...",
    expense_note_placeholder: "Xarajat haqida yozing...",
    select_staff: "Xodim tanlash",
    staff_member_label: "Xodim",
    pay_salary: "Oylik To'lash",
    pay_all_salaries: "Barchasiga To'lash",
    salary_paid: "Oylik To'landi",
    salary_paid_msg: "Oylik muvaffaqiyatli belgilandi",
    enter_amount: "Miqdorni kiriting",
    salary_payment_desc: "Oylik to'lov",
    total_deductions: "Jami Ushlanmalar",
    select_patient: "Bemorni Tanlash",
    enter_custom_category: "Kategoriya nomini kiriting...",
    add_note_details: "Izoh qo'shing...",
    distribution: "Taqsimot",
    clinic_remainder: "Klinika (Qoldiq)",
    split: "Taqsimot",
    salary_split: "Oylik",
    step_title: "Qadam nomi",
    step_title_ph: "Masalan: Ekstraksiya",
    doctor_staff: "Shifokor / Xodim",
    operation_active: "Operatsiya faol",
    stop: "To'xtatish",
    operation_successful: "Operatsiya Muvaffaqiyatli",
    all_phases_completed: "Barcha bosqichlar yakunlandi.",
    reset_tracker: "Trekerni Tiklash",
    reset_tracker_desc: "Haqiqatan ham operatsiyani noldan boshlamoqchimisiz? Barcha jarayon o'chib ketadi.",
    reset: "Tiklash",
    skip: "O'tkazish",
    operation_progress: "Operatsiya Jarayoni",
    no_operation_steps: "Operatsiya bosqichlari yo'q",
    add_phases_ph: "Masalan: Anesteziya, Ekstraksiya",
    hours_short: "Soat",
    start_operation: "Amaliyotni Boshlash",
    add: "Qo'shish",
    success: "Muvaffaqiyatli",
    copied_to_clipboard: "Nusxalandi",
  },
  ru: {
    loading: "Загрузка...",
    loading_pleasewait: "Все под контролем, ожидайте...",
    no_chat_selected: "Чат не выбран",
    select_patient_msg: "Выберите пациента из левого меню, чтобы просмотреть историю сообщений.",
    // Navigation
    management: "Управление",
    files: "Файлы",
    my_files: "Мои файлы",
    tasks_folder: "Задачи",
    notes_folder: "Заметки",
    add_note_prompt: "Добавить новую заметку",
    search_files: "Поиск файлов...",
    roles: "Роли",
    roles_management: "Управление ролями",
    add_user: "Добавить пользователя",
    search_users: "Поиск пользователей...",
    no_results_found: "Пользователи не найдены",
    no_users_found: "Пользователи не найдены",
    // Roles Specific
    edit_user: "Редактировать пользователя",
    add_user_title: "Добавить нового пользователя",
    new_password_optional: "Новый пароль (необязательно)",
    leave_blank_password: "Оставьте пустым, чтобы не менять",
    set_login_password: "Установите пароль для входа",
    role_permission: "Права доступа",
    viewer_role: "Наблюдатель (Viewer)",
    read_only_access: "Только просмотр",
    call_operator_role: "Оператор",
    leads_only_access: "Доступ только к лидам",
    nurse_role: "Медсестра",
    patients_only_access: "Доступ только к пациентам",
    create_account: "Создать аккаунт",
    save_changes: "Сохранить изменения",
    remove: "Удалить",
    only_admins_roles: "Только администраторы могут управлять ролями.",
    roles_management_subtitle: "Управление доступом для наблюдателей и операторов.",

    // Roles Toasts
    toast_password_reset_note: "Примечание: Обновление пароля требует повторного входа или сброса админом.",
    toast_user_added: "Пользователь успешно добавлен как",
    toast_user_updated: "Данные пользователя сохранены.",
    toast_user_removed: "Пользователь удален",
    toast_access_revoked: "Доступ отозван.",
    toast_remove_failed: "Не удалось удалить пользователя.",
    toast_phone_exists: "Этот номер телефона уже зарегистрирован.",
    validation_pin_error: "Пароль должен состоять ровно из 6 цифр.",
    set_login_password_placeholder: "Установите 6-значный PIN для входа",

    dashboard: "Панель управления",
    patients: "Пациенты",
    new_patient: "Новый пациент",
    help: "Помощь",
    settings: "Настройки",
    logout: "Выйти",
    search: "Поиск...",
    dr_name: "Владелец аккаунта",
    total_patients: "Всего пациентов",
    new_patients_stat: "Новые пациенты",
    total_appointments: "Всего приемов",
    requests: "Запросы",
    leads: "Лиды",
    last_month: "Прошлый месяц",
    patients_stats: "Статистика пациентов",
    monthly: "Ежемесячно",
    yearly: "Годовой",
    weekly: "Еженедельно",
    todays_appointments: "Приемы сегодня",
    see_all: "Показать все",
    patient_directory: "Каталог пациентов",
    total: "Всего",
    active: "Активные",
    name: "Имя",
    operation_date: "Дата операции",
    next_injection: "След. инъекция",
    status: "Статус",
    action: "Действие",
    none_scheduled: "Не запланировано",
    view: "Просмотр",
    back_to_list: "Назад к списку",
    edit: "Изменить",
    age: "Возраст",
    gender: "Пол",
    phone: "Телефон",
    email: "Электронная почта",
    grafts: "Количество графтов",
    technique: "Пересадка",
    select_tech: "Выберите тип",
    tech: "Тип",
    transplant_hair: "Волосы",
    transplant_eyebrow: "Брови",
    transplant_beard: "Борода",
    before_operation: "До операции",
    before_media: "Медиа до",
    upload_photo_video: "Загрузить фото/видео",
    view_photo: "Посмотреть фото",
    play_video: "Смотреть видео",
    progress: "Прогресс",
    add_photo: "Добавить фото",
    add_media: "Добавить медиа",
    injection_schedule: "График плазмотерапии",
    medically_verified: "Медицински Подтверждено",
    injection: "Инъекция",
    mark_done: "Выполнено",
    mark_missed: "Пропущено",
    new_patient_reg: "Гостевой пациент",
    edit_patient_title: "Редактирование профиля",
    full_name: "ФИО",
    first_name: "Имя",
    last_name: "Фамилия",
    phone_number: "Номер телефона",
    save_patient: "Сохранить",
    saving: "Сохранение...",
    uploading: "Загрузка...",
    cancel: "Отмена",
    click_upload: "Загрузить",
    patient_list: "Список пациентов",
    details: "Детали",
    add_new_patient: "Добавить пациента",
    journey_of_recovery: "Путь восстановления",
    today: "Сегодня",
    years: "Лет",
    no_image: "Нет фото",
    no_progress: "Нет фото прогресса.",
    no_upcoming: "Нет предстоящих инъекций.",
    plasma_injection: "Плазмотерапия",
    status_active: "Активный",
    status_recovered: "Выздоровел",
    status_observation: "Наблюдение",
    status_scheduled: "Запланировано",
    status_completed: "Завершено",
    status_missed: "Пропущено",
    status_cancelled: "Отменено",
    gender_male: "Мужской",
    gender_female: "Женский",
    gender_other: "Другой",
    add_injection: "Назначить инъекцию",
    edit_injection: "Редактировать инъекцию",
    date: "Дата",
    notes: "Заметки",
    save: "Сохранить",
    confirm_logout_title: "Выйти?",
    confirm_logout_desc: "Вы хотите выйти из системы?",
    keep_logged_in: "Остаться в системе",
    photo_label_title: "Метка времени фото",
    time_since_op: "Прошло времени",
    pinned_message: "📌 Закрепленное сообщение",
    reply_to: "Ответить",
    value: "Значение",
    unit: "Единица",
    days: "Дней",
    weeks: "Недель",
    months: "Месяцев",
    enter_notes: "Введите заметки...",
    messages: "Сообщения",
    delete: "Удалить",
    reply: "Ответить",
    copy: "Копировать",
    pin: "Закрепить",
    unpin: "Открепить",
    doctor: "Врач",
    patient: "Пациент",
    confirm_delete: "Вы уверены, что хотите удалить эту инъекцию?",
    delete_modal_title: "Вы уверены?",
    delete_warning: "Это действие нельзя отменить. Вы уверены?",
    delete_photo_title: "Вы уверены?",
    delete_photo_desc: "Вы хотите навсегда удалить это фото?",
    undo: "Отменить",
    reminder: "Напоминание",
    confirm: "Подтвердить",
    yes: "Да",
    no: "Нет",
    login_welcome: "Добро пожаловать",
    login_subtitle: "Пожалуйста, введите код доступа",
    enter_password: "Введите пароль",
    login_btn: "Войти",
    wrong_password: "Неверный пароль, попробуйте снова.",
    access_restricted: "Доступ ограничен",
    edit_profile: "Редактировать профиль",
    current_password: "Текущий пароль",
    new_password: "Новый пароль",
    schedule_for: "Расписание на",
    no_events_day: "На этот день приемов не запланировано",
    check_other_dates: "Проверьте другие даты в календаре",
    patients_scheduled: "запланировано пациентов",
    prev_page: "Назад",
    next_page: "Вперед",
    page_of: "Страница {current} из {total}",
    password_hint: "Создайте 6-значный PIN-код",
    optional_change: "(необязательно - только для изменения)",
    profile_photo: "Фото профиля",
    before_photo: "Клиническое фото (До)",
    personal_info: "Личная Информация",
    medical_details: "Медицинские Детали",
    enter_patient_details: "Введите данные пациента ниже",
    upload_image: "Загрузить изображение",
    lock_app: "Блокировка",
    app_locked: "Приложение заблокировано",
    enter_pin: "Введите PIN-код",
    unlock: "Разблокировать",
    enable_lock: "Включить блокировку",
    lock_hint: "Добавляет кнопку блокировки в меню для быстрой защиты.",
    note_title_placeholder: "Заголовок (необязательно)",
    note_content_placeholder: "Текст заметки...",
    security_settings: "Настройки безопасности",
    edit_patient: "Редактировать",
    delete_patient: "Удалить",
    delete_patient_confirm: "Вы уверены, что хотите удалить профиль пациента? Все данные, включая фото и историю, будут удалены безвозвратно.",
    login_phone: "Номер телефона",
    login_password: "Пароль",
    login_signin: "Войти",
    login_title: "Войдите в аккаунт клиники",
    delete_patient_title: "Удалить профиль пациента?",
    danger_zone: "Опасная Зона",
    login_no_account: "Обратитесь к администратору, если у вас нет аккаунта",
    login_error_no_account: "Аккаунт с этим номером не найден",
    login_error_invalid_password: "Неверный пароль",
    login_error_disabled: "Этот аккаунт отключен",
    login_error_generic: "Произошла ошибка. Попробуйте снова.",
    login_banned_msg: "Ваш аккаунт заблокирован. Пожалуйста, свяжитесь с администратором.",
    schedule_message_title: "Запланировать сообщение",
    schedule_today: "Сегодня",
    schedule_tomorrow: "Завтра",
    schedule_send_today: "Отправить сегодня в",
    schedule_send_tomorrow: "Отправить завтра в",
    schedule_send_date: "Отправить",
    schedule_at: "в",
    pick_date: "Выбрать дату",
    back: "Назад",
    alert_future_time: "Пожалуйста, выберите будущее время.",
    login_frozen_msg: "Ваш аккаунт временно заморожен. Пожалуйста, обратитесь в поддержку.",
    banned_title: "Аккаунт Заблокирован",
    banned_desc: "Ваш аккаунт был заблокирован из-за нарушения правил. Пожалуйста, свяжитесь с администратором для восстановления.",
    banned_contact_btn: "Позвонить Админу",
    banned_logout: "Выйти",
    select_language: "Язык",
    forgot_password_title: "Забыли пароль?",
    forgot_password_prompt: "Кажется, у вас возникли проблемы. Хотите восстановить пароль через Telegram?",
    no_cancel: "Нет",
    yes_recover: "Да",
    toast_profile_saved: "Профиль успешно сохранен!",
    toast_save_failed: "Не удалось сохранить",
    toast_upload_failed: "Ошибка загрузки изображения",
    toast_password_short: "Пароль должен быть не менее 6 символов",
    toast_no_session: "Нет активной сессии - выйдите и войдите снова",
    toast_patient_added: "Пациент успешно добавлен",
    toast_patient_updated: "Данные пациента обновлены",
    toast_patient_deleted: "Пациент успешно удален",
    toast_delete_failed: "Ошибка при удалении пациента",
    toast_photo_added: "Фото успешно добавлено",
    toast_photo_deleted: "Фото успешно удалено",
    injection_updated_title: "Инъекция обновлена",
    injection_updated_msg: "Изменения успешно сохранены в графике.",
    toast_injection_added: "Инъекция успешно добавлена",
    toast_injection_updated: "Инъекция успешно обновлена",
    toast_injection_deleted: "Инъекция успешно удалена",
    toast_profile_updated: "Профиль успешно обновлен!",
    permission_denied: "Отказано в доступе: у вас нет прав на это действие",
    forgot_password: "Забыли пароль? Выйти",
    forgot_password_link: "Забыли пароль?",
    reset_password_title: "Сброс Пароля",
    reset_password_desc: "Введите email и мы отправим ссылку для сброса.",
    send_link: "Отправить",
    check_email: "Проверьте email для сброса пароля!",
    email_placeholder: "Email",
    magic_link_sent: "Ссылка отправлена! Проверьте email для входа.",
    select_date: "Выберите дату",
    select_time: "Выберите время",
    hours: "Часы",
    minutes: "Минуты",
    set_time: "Установить",
    january: "Январь", february: "Февраль", march: "Март", april: "Апрель", may: "Май", june: "Июнь",
    july: "Июль", august: "Август", september: "Сентябрь", october: "Октябрь", november: "Ноябрь", december: "Декабрь",
    sun: "Вс", mon: "Пн", tue: "Вт", wed: "Ср", thu: "Чт", fri: "Пт", sat: "Сб",
    surgeries_today: "Операции сегодня",
    injections_due: "Инъекции сегодня",
    active_patients: "Активные пациенты",
    consultations: "Консультации",
    todays_operations: "Сегодняшние операции",
    live_now: "Сейчас",
    no_operations: "Нет операций",
    view_floor_map: "Карта операций",
    filter_all: "Все",
    filter_operations: "Операции",
    filter_injections: "Инъекции",
    show: "Показать",
    hide: "Скрыть",
    tomorrow: "Завтра",

    current_plan: "Текущий План",
    plan_details: "Детали Плана",
    valid_until: "СРОК ПОДПИСКИ",
    status_not_paid: "Требуется Оплата",
    status_trial: "Пробный Период",
    transaction_history: "История Платежей",
    no_transactions: "Транзакций пока нет.",
    payment_gateway: "Безопасный Платежный Шлюз",
    subscription_fee: "Стоимость Подписки",
    pay_subscription: "Оплатить подписку",

    feature_full_access: "Полный доступ к записям пациентов",
    feature_realtime: "Синхронизация данных в реальном времени",
    feature_backups: "Автоматическое резервное копирование",
    feature_sync: "Синхронизация между устройствами",
    upcoming_patients: "Предстоящие пациенты",
    operation: "Операция",
    plasma_followups: "Плазма и осмотры",
    due_within_24h: "В ТЕЧЕНИЕ 24Ч",
    routine_followup: "Плановый осмотр",
    view_master_schedule: "Просмотреть общий график",
    registration_overview: "Обзор регистрации пациентов",
    overview: "Обзор",
    upcoming_schedule: "Предстоящий график",
    account_status: "Статус Аккаунта",
    source_walkin: "Визит",
    source_referral: "Рекомендация",

    // Toasts
    success: "Успешно",
    copied_to_clipboard: "Скопировано в буфер обмена",
    toast_success_title: "Успешно!",
    saving_patient_data: "Сохранение данных пациента...",
    uploading_large_image: "Загрузка большого изображения, пожалуйста, подождите...",
    toast_error_title: "Произошла ошибка",
    toast_info_title: "Информация",
    profile_updated_title: "Профиль обновлен",
    profile_updated_msg: "Ваши изменения были успешно сохранены.",
    patient_added_title: "Пациент добавлен",
    patient_added_msg: "Новый профиль успешно создан в базе данных.",
    patient_updated_title: "Пациент обновлен",
    patient_updated_msg: "Данные пациента успешно сохранены.",
    deleted_title: "Удалено",
    patient_deleted_msg: "Данные пациента полностью удалены.",
    injection_added_title: "Инъекция добавлена",
    injection_added_msg: "Новая процедура успешно добавлена в график.",
    photo_added_title: "Фото добавлено",
    photo_added_msg: "Новое клиническое фото успешно сохранено.",
    photo_deleted_title: "Фото удалено",
    photo_deleted_msg: "Фотография успешно удалена из галереи.",
    status_updated_title: "Статус обновлен",
    status_updated_msg: "Статус инъекции успешно изменен.",
    lead_deleted_msg: "Лид успешно удален.",
    toast_note_deleted: "Заметка успешно удалена.",
    toast_note_updated: "Заметка успешно обновлена.",
    toast_note_added: "Новая заметка успешно добавлена.",
    reminder_set_title: "Напоминание установлено",
    reminder_set_msg: "Срок напоминания успешно запланирован.",
    reminder_deleted_msg: "Напоминание удалено.",
    status_frozen: "заморожен",
    status_active_msg: "активирован",
    account_frozen_msg: "Аккаунт успешно заморожен.",
    account_active_msg: "Аккаунт успешно активирован.",
    broadcast_success: "Сообщение успешно отправлено.",
    account_created: "Аккаунт успешно создан.",

    // Lock Screen
    security_check: "Проверка безопасности",
    remember_password: "Доктор, вы помните пароль?",

    // Delete Modal
    delete_modal_headline: "Мы действительно прощаемся?",
    delete_modal_subtext: "Это действие нельзя отменить. Все данные пациента, фотографии и история будут удалены безвозвратно.",
    confirm_remove_user: "Удалить пользователя?",
    confirm_remove_user_desc: "Вы уверены, что хотите удалить этого пользователя? Он больше не сможет войти в систему.",
    delete_modal_cancel: "Нет, оставить",
    delete_modal_confirm: "Да, удалить",
    delete_transaction_title: "Удалить транзакцию?",
    delete_transaction_desc: "Вы уверены, что хотите удалить эту транзакцию?",

    // Empty States
    empty_state_peace: "Пока спокойно...",
    schedule_empty_title: "Инъекций пока нет",
    schedule_empty_mascot: "Инъекции еще не запланированы. Давайте запланируем первый шаг к выздоровлению!",
    add_first_injection: "Запланировать первую инъекцию",
    next_injection_tooltip: "Следующая инъекция!",

    // Settings & Admin
    settings_desc: "Управление профилем, предпочтениями и безопасностью",
    account_id_label: "Аккаунт",
    preferences: "Предпочтения",
    notifications: "Уведомления", // Assuming I find 'notifications' or nearby key in RU
    no_notifications_yet: "Уведомлений пока нет",
    time_just_now: "Только что",
    time_minute_ago: "{m} м назад",
    time_hour_ago: "{h} ч назад",
    app_appearance: "Внешний вид",
    light_mode: "Светлая",
    security: "Безопасность",
    sound_settings: "Настройки звука",
    enable_sound: "Включить звук",
    sound_hint: "Звуковые уведомления и эффекты.",
    two_factor: "Двухфакторная аутентификация",
    verify_account_password: "Подтвердите пароль аккаунта",
    sync_pin_hint: "Требуется для сохранения нового PIN-кода как пароля аккаунта",
    logout_desc: "Завершить текущий сеанс",
    admin_control_center: "Центр управления супер-администратора",
    admin_panel: "Админ Панель",
    god_mode: "Режим бога активен",
    megaphone_title: "Мегафон",
    megaphone_desc: "Отправить мгновенье оповещение всем активным пользователям.",
    transmit: "Отправить",
    clear: "Очистить",

    // Pagination
    pagination_showing: "Показано {start}-{end} из {total} пациентов",

    // Validation
    validation_age_invalid: "Пожалуйста, введите правильный возраст (1-120)",
    validation_technique_required: "Пожалуйста, выберите метод",
    validation_date_required: "Дата операции обязательна",

    // Empty State
    empty_patient_list_title: "Пациентов Пока Нет",
    empty_patient_list_desc: "Здесь пока тихо. Добавьте нового пациента, чтобы начать!",

    // Tour Guide
    tour_welcome_title: "Добро пожаловать, Доктор!",
    tour_welcome_desc: "Я ваш помощник Graft. Давайте я покажу вам рабочий стол.",
    tour_stats_desc: "Здесь вы можете отслеживать статистику операций и инъекций.",
    tour_add_btn_desc: "Самая важная кнопка! Нажмите здесь, чтобы добавить нового пациента.",

    // Kanban
    status_new: "Новый",
    status_contacted: "Связались",
    status_photos_sent: "Фото отправлены",
    status_price_given: "Цена озвучена",
    status_booked: "Операция",
    status_lost: "Отменено",
    edit_lead: "Редактировать лид",
    add_new_lead: "Добавить новый лид",
    added: "Добавлено",
    set_lead_status: "Изменить статус",
    just_now: "Только что",
    set_reminder: "Установить напоминание",
    dont_forget_call: "Не забудьте позвонить клиенту",
    quick_select: "БЫСТРЫЙ ВЫБОР",

    // Filters
    filter_quick_filters: "Быстрые фильтры:",
    filter_today_calls: "Звонки сегодня",
    filter_this_week: "На этой неделе",
    filter_has_reminder: "Есть напоминание",
    filter_source: "Источник:",
    filter_clear_all: "Очистить все",
    filter_source_instagram: "Instagram",
    filter_source_telegram: "Telegram",
    filter_source_walkin: "Пришел сам",
    filter_source_referral: "Рекомендация",

    placeholder_type_message: "Введите сообщение...",
    status_online: "В сети",
    status_offline: "Не в сети",
    label_today: "Сегодня",
    no_messages_yet: "Сообщений пока нет",
    // Note Status
    urgency: "Срочно",
    todo: "Задача",
    note: "Заметка",
    my_notes: "Мои заметки",
    new_note: "Новая заметка",
    no_notes_found: "Заметки не найдены",
    no_patients_found: "Пациенты не найдены",

    // Staff
    staff_management: "Управление Персоналом",
    pay_all_salaries: "Выплатить всем",
    staff_subtitle: "Управление членами команды и ролями",
    add_staff: "Добавить Сотрудника",
    search_staff: "Поиск по имени или роли...",
    edit_staff: "Редактировать Сотрудника",
    add_new_staff: "Добавить Нового Сотрудника",
    staff_modal_subtitle: "Заполните данные ниже, чтобы добавить нового члена команды.",
    no_staff_found: "Сотрудники не найдены",
    add_first_staff: "Начните с добавления первого сотрудника",
    upload_photo: "Загрузить Фото",
    role: "Роль",
    save_staff: "Сохранить",
    update_staff: "Обновить Сотрудника",
    notes_placeholder: "Думай иначе...",
    role_doctor: "Врач",
    role_assistant: "Ассистент",
    role_receptionist: "Ресепшн",
    role_nurse: "Медсестра",
    role_cleaner: "Уборщик",
    role_admin: "Админ",
    role_other: "Другое",
    status_on_leave: "В отпуске",
    status_terminated: "Уволен",
    staff_added_title: "Сотрудник Добавлен",
    staff_added_msg: "Новый сотрудник успешно добавлен.",
    staff_updated_title: "Сотрудник Обновлен",
    staff_updated_msg: "Данные сотрудника обновлены.",
    staff_deleted: "Сотрудник удален.",
    total_paid: "Всего выплачено",
    delete_confirmation: "Вы уверены, что хотите удалить этого сотрудника?",

    // Finance Categories
    other: "Другое",
    custom_category: "Другая категория",
    enter_category: "Введите название категории...",
    salary: "Зарплата",
    surgery: "Операция",
    consultation: "Консультация",
    rent: "Аренда",
    equipment: "Оборудование",
    marketing: "Маркетинг",
    food: "Питание",
    utility: "Коммунальные",
    tax: "Налог",
    tax_exp: "Налог/Расход",
    distribution: "Распределение",
    clinic_remainder: "Остаток клиники",
    add_transaction: "Добавить транзакцию",
    add_payment: "Добавить платеж",
    save_payment: "Сохранить платеж",
    payment_history: "История платежей",
    amount: "Сумма",
    currency: "Валюта",
    income: "Доход",
    paid_so_far: "Оплачено",
    completed: "Завершено",
    no_payments_yet: "Платежей Пока Нет",
    no_payments_desc: "Платежные транзакции будут отображаться здесь после добавления.",
    remaining_balance: "Остаток",
    fully_paid: "Полностью Оплачено",
    partially_paid: "Частично Оплачено",
    underpaid: "Недоплачено",
    payment_progress: "Прогресс Платежей",
    last_payment: "Последний Платеж",
    expense: "Расход",
    category: "Категория",
    description: "Описание",
    expense_note_placeholder: "Напишите о расходе...",
    staff_member: "Сотрудник",

    fill_details: "Заполните детали ниже",
    transaction_details: "Детали транзакции",
    income_distribution: "Распределение дохода (Сплиты)",
    add_split: "+ Добавить сплит",
    splits_empty_state: "Добавьте сплиты для распределения дохода (напр. налог, зарплата)",
    net_income: "Чистый доход",
    gross_income: "Валовой доход",
    total_deductions: "Всего вычетов",
    confirm_income: "Подтвердить доход",
    confirm_expense: "Подтвердить расход",
    custom_category_name: "Название категории",
    review_analytics: "Обзор аналитики",
    income_statistics: "Статистика доходов и расходов",
    recent: "Недавние",
    view_all: "Посмотреть все",
    filter_by_category: "Фильтр по категории",
    no_transactions_found: "Транзакции не найдены",
    adjust_filters_hint: "Попробуйте изменить фильтры или условия поиска.",
    clear_filters: "Очистить фильтры",
    staff: "Персонал",
    all_months: "Все месяцы",
    this_month: "Этот месяц",
    finance: "Финансы",
    general_info: "Общая информация",
    transactions: "Транзакции",
    search_patients: "Поиск пациентов...",
    net_profit: "Чистая прибыль",
    total_income: "Общий доход",
    total_expenses: "Общие расходы",
    all_categories: "Все категории",
    time_range: "Временной интервал",
    transaction_type: "Тип транзакции",
    all_types: "Все типы",
    income_only: "Только доходы",
    expense_only: "Только расходы",
    tab_chat: "Чат",
    tab_scheduled: "Запланировано",
    salary_payment: "Выплата зарплаты",
    records: "записей",
    split_from: "[Сплит] ",
    split: "Сплит",
    salary_split: "Зарплата",
    step_title: "Название этапа",
    step_title_ph: "Например: Экстракция",
    doctor_staff: "Врач / Персонал",
    operation_active: "Операция активна",
    stop: "Стоп",
    operation_successful: "Операция успешна",
    all_phases_completed: "Все этапы завершены.",
    reset_tracker: "Сбросить",
    reset_tracker_desc: "Вы уверены, что хотите сбросить операцию? Весь прогресс будет удален.",
    reset: "Сброс",
    skip: "Пропустить",
    operation_progress: "Прогресс операции",
    no_operation_steps: "Этапы операции не заданы",
    add_phases_ph: "Например: Анестезия, Экстракция",
    hours_short: "Час",
    start_operation: "Начать Операцию",
    add: "Добавить",

    staff_delete_popup_title: "Удалить сотрудника?",
    staff_delete_popup_desc: "Вы уверены, что хотите удалить этого сотрудника? Это действие нельзя отменить.",

    transaction_deleted: "Удалено",
    transaction_deleted_msg: "Транзакция успешно удалена",
    error_deleting: "Ошибка удаления",
    restored: "Восстановлено",
    restored_msg: "Транзакция успешно восстановлена",
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  // Initialize from localStorage or default to 'uz'
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem('graft_language');
      return (saved === 'en' || saved === 'uz' || saved === 'ru') ? saved : 'uz';
    } catch (e) {
      return 'uz';
    }
  });

  // Wrapper to save to localStorage
  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('graft_language', lang);
  };

  // Listen for storage events (multi-tab sync)
  React.useEffect(() => {
    const handleStorageChange = (e: StorageEvent) => {
      if (e.key === 'graft_language' && e.newValue) {
        const newLang = e.newValue;
        if (newLang === 'en' || newLang === 'uz' || newLang === 'ru') {
          setLanguageState(newLang);
        }
      }
    };

    window.addEventListener('storage', handleStorageChange);
    return () => window.removeEventListener('storage', handleStorageChange);
  }, []);

  const t = (key: string): string => {
    // @ts-ignore
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
