
import React, { createContext, useState, useContext, ReactNode } from 'react';

export type Language = 'en' | 'uz' | 'ru';

export const translations = {
  en: {
    dashboard: "Dashboard",
    patients: "Patients",
    new_patient: "New Patient",
    help: "Help",
    settings: "Settings",
    logout: "Logout",
    search: "Search...",
    dr_name: "Account Owner",
    total_patients: "Total Patients",
    new_patients_stat: "New Patients",
    total_appointments: "Total Appointments",
    requests: "Requests",
    last_month: "Last Month",
    patients_stats: "Patients Statistics",
    monthly: "Monthly",
    weekly: "Weekly",
    todays_appointments: "Today's Appointments",
    see_all: "See All",
    patient_directory: "Patient Directory",
    total: "Total",
    name: "Name",
    operation_date: "Operation Date",
    next_injection: "Next Injection",
    status: "Status",
    action: "Action",
    none_scheduled: "None Scheduled",
    view: "View",
    back_to_list: "Back to List",
    age: "Age",
    gender: "Gender",
    phone: "Phone",
    email: "Email Address",
    grafts: "Graft Count",
    technique: "Technique",
    select_tech: "Select Method",
    tech: "Tech",
    before_operation: "Before Operation",
    progress: "Progress",
    add_photo: "Add Photo",
    injection_schedule: "Plasma Injection Schedule",
    injection: "Injection",
    mark_done: "Mark Done",
    mark_missed: "Missed",
    new_patient_reg: "New Patient Registration",
    edit_patient_title: "Edit Patient Profile",
    full_name: "Full Name",
    phone_number: "Phone Number",
    save_patient: "Save Patient",
    saving: "Saving...",
    cancel: "Cancel",
    click_upload: "Click to upload",
    patient_list: "Patient List",
    details: "Details",
    add_new_patient: "Add New Patient",
    today: "Today",
    years: "Years",
    no_image: "No Image",
    no_progress: "No progress photos yet.",
    no_upcoming: "No upcoming injections.",
    plasma_injection: "Plasma Injection",
    status_active: "Active",
    status_recovered: "Recovered",
    status_observation: "Observation",
    status_scheduled: "Scheduled",
    status_completed: "Completed",
    status_missed: "Missed",
    status_cancelled: "Cancelled",
    gender_male: "Male",
    gender_female: "Female",
    gender_other: "Other",
    add_injection: "Schedule Injection",
    edit_injection: "Edit Injection",
    date: "Date",
    notes: "Notes",
    save: "Save",
    confirm_logout_title: "Ready to leave?",
    confirm_logout_desc: "Are you sure you want to sign out of ProMed? You will need to log in again to access your data.",
    keep_logged_in: "Keep Logged In",
    photo_label_title: "Photo Timeline",
    time_since_op: "Time since operation",
    value: "Value",
    unit: "Unit",
    days: "Days",
    weeks: "Weeks",
    months: "Months",
    enter_notes: "Enter optional notes...",
    delete: "Delete",
    confirm_delete: "Are you sure you want to delete this injection?",
    delete_modal_title: "Delete Injection",
    delete_warning: "This action cannot be undone. Are you sure you want to permanently remove this session?",
    confirm: "Confirm",
    login_welcome: "Welcome Back",
    login_subtitle: "Please enter your access code",
    enter_password: "Enter Password",
    login_btn: "Login",
    wrong_password: "Incorrect password, please try again.",
    access_restricted: "Access Restricted",
    edit_profile: "Edit Profile",
    current_password: "Current Password",
    new_password: "New Password",
    password_hint: "Use a strong password (at least 8 characters, numbers and letters)",
    optional_change: "(optional - only to change)",
    profile_photo: "Profile Photo",
    before_photo: "Clinical Photo (Before)",
    personal_info: "Personal Information",
    medical_details: "Medical Details",
    enter_patient_details: "Enter patient details below",
    upload_image: "Upload Image",
    lock_app: "Lock App",
    app_locked: "App Locked",
    enter_pin: "Enter PIN to Unlock",
    unlock: "Unlock",
    enable_lock: "Enable Lock Screen",
    lock_hint: "Adds a lock button to the sidebar for quick security.",
    security_settings: "Security Settings",
    edit_patient: "Edit Patient",
    delete_patient: "Delete Patient",
    delete_patient_confirm: "Are you sure you want to delete this patient profile? All data including photos and history will be permanently removed.",
    login_phone: "Phone Number",
    login_password: "Password",
    login_signin: "Sign In",
    login_title: "Sign in to your clinic account",
    delete_patient_title: "Delete Patient profile?",
    danger_zone: "Danger Zone",
    login_no_account: "Contact your administrator if you don't have an account",
    login_error_no_account: "No account found with this phone number",
    login_error_invalid_password: "Invalid password",
    login_error_disabled: "This account has been disabled",
    login_error_generic: "An error occurred. Please try again.",
    select_language: "Language",
    toast_profile_saved: "Profile saved successfully!",
    toast_save_failed: "Failed to save",
    toast_upload_failed: "Image upload failed",
    toast_password_short: "Password must be at least 6 characters",
    toast_no_session: "No active session - please log out and log back in",
    toast_patient_added: "Patient added successfully",
    toast_patient_deleted: "Patient deleted successfully",
    toast_delete_failed: "Failed to delete patient",
    forgot_password: "Forgot password? Sign out",
    forgot_password_link: "Forgot your password?",
    reset_password_title: "Reset Password",
    reset_password_desc: "Enter your email and we'll send you a reset link.",
    send_link: "Send Link",
    check_email: "Check your email for the reset link!",
    email_placeholder: "Email",
    magic_link_sent: "Magic link sent! Check your email to log in.",
    select_date: "Select Date",
    january: "January", february: "February", march: "March", april: "April", may: "May", june: "June",
    july: "July", august: "August", september: "September", october: "October", november: "November", december: "December",
    sun: "Su", mon: "Mo", tue: "Tu", wed: "We", thu: "Th", fri: "Fr", sat: "Sa"
  },
  uz: {
    dashboard: "Boshqaruv paneli",
    patients: "Bemorlar",
    new_patient: "Yangi Bemor",
    help: "Yordam",
    settings: "Sozlamalar",
    logout: "Chiqish",
    search: "Qidirish...",
    dr_name: "Account Owner",
    total_patients: "Jami Bemorlar",
    new_patients_stat: "Yangi Bemorlar",
    total_appointments: "Jami Uchrashuvlar",
    requests: "So'rovlar",
    last_month: "O'tgan oy",
    patients_stats: "Bemorlar Statistikasi",
    monthly: "Oylik",
    weekly: "Haftalik",
    todays_appointments: "Bugungi Uchrashuvlar",
    see_all: "Hammasini ko'rish",
    patient_directory: "Bemorlar Ro'yxati",
    total: "Jami",
    name: "Ism",
    operation_date: "Operatsiya Sanasi",
    next_injection: "Keyingi Inyeksiya",
    status: "Holat",
    action: "Amal",
    none_scheduled: "Rejalashtirilmagan",
    view: "Ko'rish",
    back_to_list: "Ro'yxatga qaytish",
    age: "Yosh",
    gender: "Jins",
    phone: "Telefon",
    email: "Email Manzili",
    grafts: "Graftlar Soni",
    technique: "Texnologiya",
    select_tech: "Usulni tanlang",
    tech: "Texnologiya",
    before_operation: "Operatsiyadan oldin",
    progress: "Jarayon",
    add_photo: "Rasm qo'shish",
    injection_schedule: "Plazma Inyeksiya Jadvali",
    injection: "Inyeksiya",
    mark_done: "Bajarildi",
    mark_missed: "O'tkazib yuborilgan",
    new_patient_reg: "Yangi Bemor Ro'yxati",
    edit_patient_title: "Bemor Profilini Tahrirlash",
    full_name: "To'liq Ism",
    phone_number: "Telefon Raqami",
    save_patient: "Bemorni Saqlash",
    saving: "Saqlanmoqda...",
    cancel: "Bekor qilish",
    click_upload: "Rasm yuklash",
    patient_list: "Bemorlar Ro'yxati",
    details: "Tafsilotlar",
    add_new_patient: "Yangi Bemor Qo'shish",
    today: "Bugun",
    years: "Yosh",
    no_image: "Rasm yo'q",
    no_progress: "Hozircha jarayon rasmlari yo'q.",
    no_upcoming: "Kutilayotgan inyeksiyalar yo'q.",
    plasma_injection: "Plazma Inyeksiyasi",
    status_active: "Faol",
    status_recovered: "Tuzalgan",
    status_observation: "Kuzatuvda",
    status_scheduled: "Rejalashtirilgan",
    status_completed: "Bajarildi",
    status_missed: "O'tkazib yuborildi",
    status_cancelled: "Bekor qilindi",
    gender_male: "Erkak",
    gender_female: "Ayol",
    gender_other: "Boshqa",
    add_injection: "Inyeksiya Belgilash",
    edit_injection: "Inyeksiyani Tahrirlash",
    date: "Sana",
    notes: "Izohlar",
    save: "Saqlash",
    confirm_logout_title: "Chiqishga tayyormisiz?",
    confirm_logout_desc: "Haqiqatan ham ProMed'dan chiqmoqchimisiz? Ma'lumotlaringizga qayta kirish uchun tizimga kirishingiz kerak bo'ladi.",
    keep_logged_in: "Tizimda qolish",
    photo_label_title: "Rasm Vaqti",
    time_since_op: "Operatsiyadan o'tgan vaqt",
    value: "Qiymat",
    unit: "Birlik",
    days: "Kun",
    weeks: "Hafta",
    months: "Oy",
    enter_notes: "Izoh qoldiring...",
    delete: "O'chirish",
    confirm_delete: "Ushbu inyeksiyani o'chirmoqchimisiz?",
    delete_modal_title: "Inyeksiyani O'chirish",
    delete_warning: "Ushbu amalni ortga qaytarib bo'lmaydi. Ushbu seansni butunlay o'chirib tashlashga ishonchingiz komilmi?",
    confirm: "Tasdiqlash",
    login_welcome: "Xush kelibsiz",
    login_subtitle: "Iltimos, kirish kodini kiriting",
    enter_password: "Parolni kiriting",
    login_btn: "Kirish",
    wrong_password: "Parol noto'g'ri, iltimos qayta urinib ko'ring.",
    access_restricted: "Kirish Cheklangan",
    edit_profile: "Profilni Tahrirlash",
    current_password: "Joriy Parol",
    new_password: "Yangi Parol",
    password_hint: "Kuchli paroldan foydalaning (kamida 8 ta belgi, raqamlar va harflar)",
    optional_change: "(ixtiyoriy - faqat o'zgartirish uchun)",
    profile_photo: "Profil Rasmi",
    before_photo: "Klinik Rasm (Oldin)",
    personal_info: "Shaxsiy Ma'lumotlar",
    medical_details: "Tibbiy Tafsilotlar",
    enter_patient_details: "Quyida bemor tafsilotlarini kiriting",
    upload_image: "Rasm yuklash",
    lock_app: "Ilovani Qulflash",
    app_locked: "Ilova Qulflangan",
    enter_pin: "PIN kodni kiriting",
    unlock: "Ochish",
    enable_lock: "Qulf ekranini yoqish",
    lock_hint: "Xavfsizlik uchun yon panelga qulf tugmasini qo'shadi.",
    security_settings: "Xavfsizlik Sozlamalari",
    edit_patient: "Tahrirlash",
    delete_patient: "O'chirish",
    delete_patient_confirm: "Haqiqatan ham ushbu bemor profilini o'chirmoqchimisiz? Barcha ma'lumotlar, shu jumladan rasmlar va tarix butunlay o'chiriladi.",
    login_phone: "Telefon Raqami",
    login_password: "Parol",
    login_signin: "Kirish",
    login_title: "Klinika hisobingizga kiring",
    delete_patient_title: "Bemorni o'chirib tashlaysizmi?",
    danger_zone: "Xavfli Hudud",
    login_no_account: "Hisobingiz bo'lmasa, administratoringizga murojaat qiling",
    login_error_no_account: "Bu telefon raqami bilan hisob topilmadi",
    login_error_invalid_password: "Parol noto'g'ri",
    login_error_disabled: "Bu hisob o'chirilgan",
    login_error_generic: "Xatolik yuz berdi. Iltimos, qayta urinib ko'ring.",
    select_language: "Til",
    toast_profile_saved: "Profil muvaffaqiyatli saqlandi!",
    toast_save_failed: "Saqlashda xatolik",
    toast_upload_failed: "Rasm yuklashda xatolik",
    toast_password_short: "Parol kamida 6 ta belgidan iborat bo'lishi kerak",
    toast_no_session: "Faol seans yo'q - iltimos, chiqib qayta kiring",
    toast_patient_added: "Bemor muvaffaqiyatli qo'shildi",
    toast_patient_deleted: "Bemor muvaffaqiyatli o'chirildi",
    toast_delete_failed: "Bemorni o'chirish muvaffaqiyatsiz tugadi",
    forgot_password: "Parolni unutdingizmi? Chiqish",
    forgot_password_link: "Parolingizni unutdingizmi?",
    reset_password_title: "Parolni Tiklash",
    reset_password_desc: "Emailingizni kiriting, sizga qayta tiklash havolasini yuboramiz.",
    send_link: "Havola Yuborish",
    check_email: "Qayta tiklash havolasi uchun emailingizni tekshiring!",
    email_placeholder: "Email",
    forgot_password_confirm: "Parolni tiklash uchun tizimdan chiqishingiz kerak. Ma'lumotlaringiz xavfsiz saqlanadi.",
    magic_link_sent: "Sehrli havola yuborildi! Kirish uchun emailingizni tekshiring.",
    select_date: "Sanani tanlang",
    january: "Yanvar", february: "Fevral", march: "Mart", april: "Aprel", may: "May", june: "Iyun",
    july: "Iyul", august: "Avgust", september: "Sentyabr", october: "Oktyabr", november: "Noyabr", december: "Dekabr",
    sun: "Yak", mon: "Du", tue: "Se", wed: "Cho", thu: "Pay", fri: "Ju", sat: "Sha"
  },
  ru: {
    dashboard: "Панель управления",
    patients: "Пациенты",
    new_patient: "Новый пациент",
    help: "Помощь",
    settings: "Настройки",
    logout: "Выйти",
    search: "Поиск...",
    dr_name: "Владелец аккаунта",
    total_patients: "Всего пациентов",
    new_patients_stat: "Новые пациенты",
    total_appointments: "Всего приемов",
    requests: "Запросы",
    last_month: "Прошлый месяц",
    patients_stats: "Статистика пациентов",
    monthly: "Ежемесячно",
    weekly: "Еженедельно",
    todays_appointments: "Приемы сегодня",
    see_all: "Показать все",
    patient_directory: "Каталог пациентов",
    total: "Всего",
    name: "Имя",
    operation_date: "Дата операции",
    next_injection: "След. инъекция",
    status: "Статус",
    action: "Действие",
    none_scheduled: "Не запланировано",
    view: "Просмотр",
    back_to_list: "Назад к списку",
    age: "Возраст",
    gender: "Пол",
    phone: "Телефон",
    email: "Электронная почта",
    grafts: "Количество графтов",
    technique: "Технология",
    select_tech: "Выберите метод",
    tech: "Технология",
    before_operation: "До операции",
    progress: "Прогресс",
    add_photo: "Добавить фото",
    injection_schedule: "График плазмотерапии",
    injection: "Инъекция",
    mark_done: "Выполнено",
    mark_missed: "Пропущено",
    new_patient_reg: "Регистрация пациента",
    edit_patient_title: "Редактирование профиля",
    full_name: "ФИО",
    phone_number: "Номер телефона",
    save_patient: "Сохранить",
    saving: "Сохранение...",
    cancel: "Отмена",
    click_upload: "Загрузить",
    patient_list: "Список пациентов",
    details: "Детали",
    add_new_patient: "Добавить пациента",
    today: "Сегодня",
    years: "Лет",
    no_image: "Нет фото",
    no_progress: "Нет фото прогресса.",
    no_upcoming: "Нет предстоящих инъекций.",
    plasma_injection: "Плазмотерапия",
    status_active: "Активный",
    status_recovered: "Выздоровел",
    status_observation: "Наблюдение",
    status_scheduled: "Запланировано",
    status_completed: "Завершено",
    status_missed: "Пропущено",
    status_cancelled: "Отменено",
    gender_male: "Мужской",
    gender_female: "Женский",
    gender_other: "Другой",
    add_injection: "Назначить инъекцию",
    edit_injection: "Редактировать инъекцию",
    date: "Дата",
    notes: "Заметки",
    save: "Сохранить",
    confirm_logout_title: "Готовы выйти?",
    confirm_logout_desc: "Вы уверены, что хотите выйти из ProMed? Вам нужно будет снова войти в систему, чтобы получить доступ к своим данным.",
    keep_logged_in: "Остаться в системе",
    photo_label_title: "Метка времени фото",
    time_since_op: "Время с операции",
    value: "Значение",
    unit: "Единица",
    days: "Дней",
    weeks: "Недель",
    months: "Месяцев",
    enter_notes: "Введите заметки...",
    delete: "Удалить",
    confirm_delete: "Вы уверены, что хотите удалить эту инъекцию?",
    delete_modal_title: "Удалить инъекцию",
    delete_warning: "Это действие нельзя отменить. Вы уверены?",
    confirm: "Подтвердить",
    login_welcome: "Добро пожаловать",
    login_subtitle: "Пожалуйста, введите код доступа",
    enter_password: "Введите пароль",
    login_btn: "Войти",
    wrong_password: "Неверный пароль, попробуйте снова.",
    access_restricted: "Доступ ограничен",
    edit_profile: "Редактировать профиль",
    current_password: "Текущий пароль",
    new_password: "Новый пароль",
    password_hint: "Используйте надежный пароль (минимум 8 символов, цифры и буквы)",
    optional_change: "(необязательно - только для изменения)",
    profile_photo: "Фото профиля",
    before_photo: "Клиническое фото (До)",
    personal_info: "Личная Информация",
    medical_details: "Медицинские Детали",
    enter_patient_details: "Введите данные пациента ниже",
    upload_image: "Загрузить изображение",
    lock_app: "Блокировка",
    app_locked: "Приложение заблокировано",
    enter_pin: "Введите PIN-код",
    unlock: "Разблокировать",
    enable_lock: "Включить блокировку",
    lock_hint: "Добавляет кнопку блокировки в меню для быстрой защиты.",
    security_settings: "Настройки безопасности",
    edit_patient: "Редактировать",
    delete_patient: "Удалить",
    delete_patient_confirm: "Вы уверены, что хотите удалить профиль пациента? Все данные, включая фото и историю, будут удалены безвозвратно.",
    login_phone: "Номер телефона",
    login_password: "Пароль",
    login_signin: "Войти",
    login_title: "Войдите в аккаунт клиники",
    delete_patient_title: "Удалить профиль пациента?",
    danger_zone: "Опасная Зона",
    login_no_account: "Обратитесь к администратору, если у вас нет аккаунта",
    login_error_no_account: "Аккаунт с этим номером не найден",
    login_error_invalid_password: "Неверный пароль",
    login_error_disabled: "Этот аккаунт отключен",
    login_error_generic: "Произошла ошибка. Попробуйте снова.",
    select_language: "Язык",
    toast_profile_saved: "Профиль успешно сохранен!",
    toast_save_failed: "Не удалось сохранить",
    toast_upload_failed: "Ошибка загрузки изображения",
    toast_password_short: "Пароль должен быть не менее 6 символов",
    toast_no_session: "Нет активной сессии - выйдите и войдите снова",
    toast_patient_added: "Пациент успешно добавлен",
    toast_patient_deleted: "Пациент успешно удален",
    toast_delete_failed: "Не удалось удалить пациента",
    forgot_password: "Забыли пароль? Выйти",
    forgot_password_link: "Забыли пароль?",
    reset_password_title: "Сброс Пароля",
    reset_password_desc: "Введите email и мы отправим ссылку для сброса.",
    send_link: "Отправить",
    check_email: "Проверьте email для сброса пароля!",
    email_placeholder: "Email",
    magic_link_sent: "Ссылка отправлена! Проверьте email для входа.",
    select_date: "Выберите дату",
    january: "Январь", february: "Февраль", march: "Март", april: "Апрель", may: "Май", june: "Июнь",
    july: "Июль", august: "Август", september: "Сентябрь", october: "Октябрь", november: "Ноябрь", december: "Декабрь",
    sun: "Вс", mon: "Пн", tue: "Вт", wed: "Ср", thu: "Чт", fri: "Пт", sat: "Сб"
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('uz');

  const t = (key: string): string => {
    // @ts-ignore
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
